// Native (Linux) test harness for the vehicle dynamics (src/sim/vehicle_sim*.cpp).
// Build: tests/vehicle/build.sh [output]   (mirrors the world sources included by src/main.cpp)
// Usage: test_vehicle [--synthetic] [--real] [--class NAME] [--models] [--perf] [--out FILE]
//   --synthetic  proving-ground telemetry for every class (stand-in models unless --models)
//   --models     use the real models from src/sim/vehicle_models.cpp (when present)
//   --real       drive on the generated world (roads, curbs, bridges, buildings)
#include "../../tools/native_stubs.cpp"
#include "../../src/core/math.cpp"
#include "../../src/core/noise.cpp"
#include "../../src/core/jobs.cpp"
#include "../../src/render/mesh.cpp"
// world sources: the same files (and order) as src/main.cpp, generated by tests/vehicle/build.sh
#include "vt_world_includes.h"
#include "../../src/sim/physics.cpp"
#if __has_include("../../src/sim/vehicle_models.cpp")
#include "../../src/sim/vehicle_models.cpp"
#define HAVE_MODELS 1
#endif
#include "../../src/sim/vehicle_sim.cpp"
#include "harness.h"
#include "realworld.h"
#include <thread>

using namespace VT;

namespace VT {

FILE* gOut = stdout;
ProvingGround* gPG = nullptr;
std::vector<std::string> gIssues;

void issue(const char* fmt, ...) {
    char buf[1024];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    gIssues.push_back(buf);
}

const vec3 kPadStart(-4800.f, 0.f, 0.f);

// ---------------------------------------------------------------------------------------------------------------
// Car / bike tests
struct CarReport {
    std::string name;
    VehicleClass cls;
    float t100 = -1, topSpeed = 0, brake100 = -1, latG = 0, laneChangeBeta = 0, laneOk = 0, hb180 = -1, hbTime = -1;
    float jumpPitch = 0, jumpRoll = 0, jumpBounces = 0, jumpUpright = 0, jumpHeadingErr = 0;
    float wallRebound = 0, wallPen = 0, wallHealth = 0, wallEngine = 0, wallStopDist = 0;
    float rollMax = 0, rollLift = 0, rolledOver = 0;
    float curbSlow = 0, curbAngle = 0;
    float propBrokeFast = 0, propDv = 0, propBrokeSlow = 0;
    float flipRest = 0, flipBack = -1;
    float sinkTime = -1, engineDeadTime = -1, floatTime = 0;
    float tunnel = 0;
    float jitterT100 = -1;
    float sleepTime = -1;
    double usPerStep = 0, usSleep = 0;
    // bikes
    float lean10 = 0, lean20 = 0, lean30 = 0, lockLean = 0, radius20 = 0, wheelieMax = 0, wheelieTime = 0, stoppieMax = 0, crashEject = 0, parkedLean = 0;
};

float accelTo(Runner& r, float v, float tmax) {
    return r.run(tmax, [](VehicleControls& c, Runner&) { c.throttle = 1.f; },
                 [&](Runner& q) { return q.s.forwardSpeed() >= v; });
}

int gTrace = 0;
bool gWheelTrace = false;
const char* gTraceScenario = nullptr;
struct ScenarioTrace {
    Runner& r;
    ScenarioTrace(Runner& rr, const char* name) : r(rr) {
        r.scenario = name;
        r.traceEvery = (gTrace && (!gTraceScenario || !strcmp(gTraceScenario, name))) ? gTrace : 0;
        r.wheelTrace = gWheelTrace;
    }
};

void testCar(const VehicleModel& m, CarReport& rep) {
    gPG->resetColliders();
    bool bike = m.cls == VC_MOTORBIKE || m.cls == VC_SCOOTER;
    Runner r;
    // ---- 0-100 and top speed ----
    ScenarioTrace st_accel(r, "accel");
    r.init(m, kPadStart, -kHalfPi);  // heading +x
    rep.t100 = accelTo(r, 27.78f, 40.f);
    float vmax = 0.f;
    float lastV = 0.f, stableT = 0.f;
    r.run(90.f, [](VehicleControls& c, Runner&) { c.throttle = 1.f; },
          [&](Runner& q) {
              float v = q.s.forwardSpeed();
              vmax = Max(vmax, v);
              stableT = fabsf(v - lastV) < 0.002f ? stableT + 1.f / 120.f : 0.f;
              lastV = v;
              return q.pos().x > 2800.f || stableT > 3.f;
          });
    rep.topSpeed = vmax;
    // ---- braking 100-0 ----
    ScenarioTrace st_brake(r, "brake");
    r.init(m, kPadStart, -kHalfPi);
    if (accelTo(r, 27.9f, 40.f) > 0.f) {
        vec3 p0 = r.pos();
        float tb = r.run(20.f, [](VehicleControls& c, Runner&) { c.brake = 1.f; }, [](Runner& q) { return q.s.forwardSpeed() < 0.3f; });
        rep.brake100 = tb > 0.f ? length(r.pos() - p0) : -1.f;
    }
    // ---- skidpad (R = 45 m circle, speed ramps until the vehicle cannot hold the line) ----
    ScenarioTrace st_skidpad(r, "skidpad");
    {
        float R0 = 45.f;
        vec2 C(-4000.f, 80.f);
        r.init(m, vec3(C.x + R0, C.y, 0.f), 0.f);  // on the circle, heading +y (counter-clockwise)
        float vT = 8.f, best = 0.f, acc = 0.f, steerCmd = -0.3f;
        vec3 vPrev(0.f);
        int n = 0;
        r.run(90.f,
              [&](VehicleControls& c, Runner& q) {
                  // integral yaw-rate controller (works for cars and lean-steered bikes) + radius correction
                  vec2 p = q.pos().xy() - C;
                  float v = Max(q.s.speed(), 1.f);
                  float ey = length(p) - R0;
                  float eyDot = dot(q.s.body.vel.xy(), normalize(p));
                  float rDes = v / R0 + 0.06f * ey + 0.25f * eyDot;
                  float er = rDes - q.s.body.angVel.z;
                  steerCmd = Clamp(steerCmd - er * 1.2f / 120.f, -1.f, 1.f);
                  c.steer = Clamp(steerCmd - er * 1.0f, -1.f, 1.f);
                  holdSpeed(c, q, vT);
                  vT += 0.25f / 120.f;
              },
              [&](Runner& q) {
                  vec2 p = q.pos().xy() - C;
                  float err = fabsf(length(p) - R0);
                  vec3 vNow = q.s.body.vel;
                  vec3 dv = (vNow - vPrev) * 120.f;
                  vPrev = vNow;
                  float a = length(cross(vNow, dv)) / Max(length(vNow), 1.f) / 9.81f;
                  float slipMax = 0.f;
                  for (int i = 0; i < q.s.wheelCount; i++) slipMax = Max(slipMax, q.s.wheels[i].slip);
                  bool clean = q.s.wheelsOnGround == q.s.wheelCount && slipMax < 1.2f && !q.s.riderOff && q.s.speed() > 5.f;
                  if (err < 2.5f && clean) {
                      acc += a;
                      n++;
                      if (n >= 120) {
                          best = Max(best, acc / n);
                          acc = 0.f;
                          n = 0;
                      }
                  }
                  return err > 6.f;
              });
        rep.latG = best;
    }
    // ---- lane change at 90 km/h (bikes 80): 3.5 m offset over 25 m and back ----
    ScenarioTrace st_lane(r, "lane");
    {
        r.init(m, kPadStart + vec3(0, -40.f, 0), -kHalfPi);
        float vT = bike ? 22.f : 25.f;
        accelTo(r, vT, 40.f);
        float x0 = r.pos().x, betaMax = 0.f;
        bool spun = false;
        r.run(8.f,
              [&](VehicleControls& c, Runner& q) {
                  float dx = q.pos().x - x0;
                  float yOff = dx < 20.f ? 0.f : (dx < 45.f ? 3.5f * SmoothStep(20.f, 45.f, dx) : (dx < 70.f ? 3.5f : 3.5f * (1.f - SmoothStep(70.f, 95.f, dx))));
                  c.steer = steerTo(q, vec2(q.pos().x + 18.f, -40.f + yOff), 3.f);
                  holdSpeed(c, q, vT);
              },
              [&](Runner& q) {
                  vec3 v = q.s.body.vel;
                  float beta = fabsf(atan2f(dot(v, q.s.right()), dot(v, q.s.forward())));
                  betaMax = Max(betaMax, beta);
                  if (beta > 0.5f) spun = true;
                  return false;
              });
        rep.laneChangeBeta = betaMax * kRadToDeg;
        // harsh driver error: full left 0.45 s, full right 0.45 s at 100 km/h
        r.init(m, kPadStart + vec3(0, 40.f, 0), -kHalfPi);
        accelTo(r, bike ? 25.f : 27.8f, 40.f);
        float t0 = r.t;
        r.run(6.f,
              [&](VehicleControls& c, Runner& q) {
                  float tt = q.t - t0;
                  c.steer = tt < 0.45f ? -1.f : (tt < 0.9f ? 1.f : 0.f);
                  c.throttle = 0.3f;
              },
              [&](Runner& q) {
                  vec3 v = q.s.body.vel;
                  float beta = fabsf(atan2f(dot(v, q.s.right()), dot(v, q.s.forward())));
                  if (beta > 0.6f && q.s.speed() > 5.f) spun = true;
                  return false;
              });
        rep.laneOk = spun ? 0.f : 1.f;
    }
    // ---- handbrake 180 at 60 km/h (cars) ----
    ScenarioTrace st_hb180(r, "hb180");
    if (!bike) {
        r.init(m, kPadStart + vec3(0, 100.f, 0), -kHalfPi);
        accelTo(r, 16.7f, 30.f);
        float h0 = r.heading(), t0 = r.t, maxTurn = 0.f;
        float tDone = r.run(6.f,
                            [&](VehicleControls& c, Runner& q) {
                                float tt = q.t - t0;
                                c.steer = tt < 1.4f ? -1.f : 0.f;
                                c.handbrake = tt < 1.2f;
                            },
                            [&](Runner& q) {
                                float d = fabsf(wrapPi(q.heading() - h0));
                                maxTurn = Max(maxTurn, d);
                                return d > 150.f * kDegToRad;
                            });
        rep.hb180 = maxTurn * kRadToDeg;
        rep.hbTime = tDone;
    }
    // ---- 2 m ramp at 90 km/h ----
    ScenarioTrace st_jump(r, "jump");
    {
        float vJ = 25.f;
        r.init(m, vec3(600.f, 60.f, 0.f), -kHalfPi);
        r.run(40.f,
              [&](VehicleControls& c, Runner& q) {
                  c.steer = steerTo(q, vec2(q.pos().x + 25.f, 60.f), 2.f);
                  holdSpeed(c, q, vJ);
                  if (q.pos().x > 960.f) c.steer = steerTo(q, vec2(q.pos().x + 25.f, 60.f), 1.f);
              },
              [&](Runner& q) { return q.pos().x > 1019.f; });
        float h0 = r.heading();
        float pMax = 0.f, rMax = 0.f;
        int bounces = 0;
        bool landed = false;
        int lastW = r.s.wheelsOnGround;
        float tLand = -1.f;
        r.run(6.f,
              [&](VehicleControls& c, Runner& q) { holdSpeed(c, q, vJ); },
              [&](Runner& q) {
                  pMax = Max(pMax, fabsf(q.pitch()));
                  rMax = Max(rMax, fabsf(q.roll()));
                  int w = q.s.wheelsOnGround;
                  if (!landed && w > 0 && q.pos().x > 1030.f) {
                      landed = true;
                      tLand = q.t;
                  }
                  if (landed && lastW == q.s.wheelsOnGround && false) bounces++;
                  if (landed && lastW > 0 && w == 0) bounces++;
                  lastW = w;
                  return landed && q.t - tLand > 3.f;
              });
        rep.jumpPitch = pMax * kRadToDeg;
        rep.jumpRoll = rMax * kRadToDeg;
        rep.jumpBounces = (float)bounces;
        rep.jumpUpright = r.s.up().z;
        rep.jumpHeadingErr = fabsf(wrapPi(r.heading() - h0)) * kRadToDeg;
    }
    // ---- wall at 60 km/h ----
    ScenarioTrace st_wall(r, "wall");
    {
        r.init(m, vec3(1700.f, 20.f, 0.f), -kHalfPi);
        float vW = 16.7f;
        r.run(30.f,
              [&](VehicleControls& c, Runner& q) {
                  c.steer = steerTo(q, vec2(q.pos().x + 20.f, 20.f), 2.f);
                  holdSpeed(c, q, vW);
              },
              [&](Runner& q) { return q.pos().x > 1990.f - m.boxHalf.y - 3.f; });
        float front0 = 0.f, maxPen = 0.f, minV = 1e9f, reb = 0.f;
        float h0 = r.s.health;
        r.run(3.f,
              [&](VehicleControls& c, Runner& q) { c.throttle = q.t < 0.f ? 1.f : 0.f; },
              [&](Runner& q) {
                  vec3 f = q.s.forward();
                  vec3 frontPt = q.pos() + rotate(q.s.body.rot, m.boxCenter + vec3(0, m.boxHalf.y, 0));
                  (void)f;
                  maxPen = Max(maxPen, frontPt.x - 2000.f);
                  minV = Min(minV, q.s.body.vel.x);
                  return false;
              });
        (void)front0;
        reb = -minV;
        rep.wallRebound = reb;
        rep.wallPen = maxPen;
        rep.wallHealth = r.s.health;
        rep.wallEngine = r.s.engineHealth;
        (void)h0;
    }
    // ---- 60 m/s wall hit: no tunnelling ----
    ScenarioTrace st_tunnel(r, "tunnel");
    {
        r.init(m, vec3(1900.f, -20.f, 0.f), -kHalfPi);
        r.s.body.vel = vec3(60.f, 0.f, 0.f);
        for (int i = 0; i < r.s.wheelCount; i++) r.s.wheels[i].spinVel = 60.f / m.wheels[i].radius;
        r.run(3.f, [](VehicleControls& c, Runner&) { c.throttle = 1.f; }, [](Runner&) { return false; });
        rep.tunnel = r.pos().x > 2000.f ? 1.f : 0.f;
    }
    // ---- rollover: step steer at 100 km/h (cars) ----
    ScenarioTrace st_rollover(r, "rollover");
    if (!bike) {
        r.init(m, kPadStart + vec3(0, -100.f, 0), -kHalfPi);
        accelTo(r, 27.8f, 40.f);
        float t0 = r.t, rollMax = 0.f;
        int liftMax = 0;
        bool over = false;
        r.run(4.f,
              [&](VehicleControls& c, Runner& q) {
                  c.steer = 1.f;
                  c.throttle = 0.5f;
              },
              [&](Runner& q) {
                  rollMax = Max(rollMax, fabsf(q.roll()));
                  int off = 0;
                  for (int i = 0; i < q.s.wheelCount; i++) off += !q.s.wheels[i].contact;
                  if (q.t - t0 > 0.2f) liftMax = Max(liftMax, off);
                  if (q.s.up().z < 0.3f) over = true;
                  return false;
              });
        rep.rollMax = rollMax * kRadToDeg;
        rep.rollLift = (float)liftMax;
        rep.rolledOver = over ? 1.f : 0.f;
        // harsher: handbrake + full lock at 100 km/h
        r.init(m, kPadStart + vec3(0, -130.f, 0), -kHalfPi);
        accelTo(r, 27.8f, 40.f);
        t0 = r.t;
        r.run(4.f,
              [&](VehicleControls& c, Runner& q) {
                  c.steer = 1.f;
                  c.handbrake = q.t - t0 < 1.f;
              },
              [&](Runner& q) {
                  if (q.s.up().z < 0.3f) over = true;
                  rollMax = Max(rollMax, fabsf(q.roll()));
                  return false;
              });
        if (over) rep.rolledOver = 1.f;
    }
    // ---- curb: cross a street with 0.15 m sidewalks (up, down, up, down) at 3 m/s straight and 10 m/s at 30 deg ----
    ScenarioTrace st_curb(r, "curb");
    {
        r.init(m, vec3(0.f, -120.f, 0.f), 0.f);  // heading north across the street at y = -100
        float zMax = 0.f, z0 = (float)r.s.body.pos.z;
        float tc = r.run(20.f,
              [&](VehicleControls& c, Runner& q) {
                  holdSpeed(c, q, 3.f);
                  c.steer = steerTo(q, vec2(0.f, q.pos().y + 10.f));
              },
              [&](Runner& q) {
                  zMax = Max(zMax, (float)q.s.body.pos.z - z0);
                  return q.pos().y > -85.f;
              });
        rep.curbSlow = tc > 0.f ? zMax : -1.f;
        r.init(m, vec3(-40.f, -125.f, 0.f), -kPi / 3.f);  // 30 degrees to the curb line
        zMax = 0.f;
        z0 = (float)r.s.body.pos.z;
        tc = r.run(15.f,
              [&](VehicleControls& c, Runner& q) { holdSpeed(c, q, 10.f); },
              [&](Runner& q) {
                  zMax = Max(zMax, (float)q.s.body.pos.z - z0);
                  return q.pos().y > -85.f;
              });
        rep.curbAngle = tc > 0.f ? zMax : -1.f;
    }
    // ---- breakable props: streetlight at 15 m/s breaks, at 2 m/s it holds ----
    ScenarioTrace st_props(r, "props");
    {
        gPG->resetColliders();
        r.init(m, vec3(1420.f, 0.f, 0.f), -kHalfPi);
        float v0 = 0.f, v1 = 0.f;
        r.run(20.f, [&](VehicleControls& c, Runner& q) { holdSpeed(c, q, 15.f); c.steer = steerTo(q, vec2(1600.f, 0.f)); },
              [&](Runner& q) { return q.pos().x > 1500.f - m.boxHalf.y - 1.5f; });
        v0 = r.s.forwardSpeed();
        int broke = 0;
        r.run(1.f, [&](VehicleControls& c, Runner&) {}, [&](Runner& q) {
            broke += q.s.brokenCount;
            return false;
        });
        v1 = r.s.forwardSpeed();
        rep.propBrokeFast = (float)broke;
        rep.propDv = v0 - v1;
        r.init(m, vec3(1480.f, 30.f, 0.f), -kHalfPi);
        broke = 0;
        r.run(8.f, [&](VehicleControls& c, Runner& q) { holdSpeed(c, q, 2.f); c.steer = steerTo(q, vec2(1600.f, 30.f)); },
              [&](Runner& q) {
                  broke += q.s.brokenCount;
                  return false;
              });
        rep.propBrokeSlow = (float)broke + (r.pos().x > 1500.f ? 10.f : 0.f);
    }
    // ---- upside down: rests on the roof, flip-back with input (cars) ----
    ScenarioTrace st_flip(r, "flip");
    if (!bike) {
        r.init(m, vec3(-3000.f, -60.f, 0.f), 0.f);
        r.s.body.rot = quatAxisAngle(vec3(0, 1, 0), kPi) * r.s.body.rot;
        r.s.body.pos.z += 2.5;
        r.run(4.f, [](VehicleControls&, Runner&) {}, [](Runner&) { return false; });
        float jit = length(r.s.body.vel) + length(r.s.body.angVel);
        rep.flipRest = r.s.up().z < -0.8f && jit < 0.05f ? 1.f : 0.f;
        float tf = r.run(8.f, [](VehicleControls& c, Runner&) { c.steer = 1.f; }, [](Runner& q) { return q.s.up().z > 0.9f && q.s.wheelsOnGround >= 3; });
        rep.flipBack = tf;
    }
    // ---- drive off the pier into deep water: floats, floods, engine dies ----
    ScenarioTrace st_lake(r, "lake");
    {
        r.init(m, vec3(2800.f, -600.f, 0.f), -kHalfPi);
        float tIn = -1.f;
        r.run(60.f,
              [&](VehicleControls& c, Runner& q) {
                  holdSpeed(c, q, 12.f);
                  c.steer = steerTo(q, vec2(q.pos().x + 20.f, -600.f));
              },
              [&](Runner& q) {
                  if (tIn < 0.f && q.s.inWater) tIn = q.t;
                  float roofDepth = q.s.waterDepth - (m.boxCenter.z + m.boxHalf.z);
                  if (tIn >= 0.f && roofDepth < 0.f) rep.floatTime = q.t - tIn;
                  if (rep.engineDeadTime < 0.f && q.s.engineFlooded && tIn >= 0.f) rep.engineDeadTime = q.t - tIn;
                  if (tIn >= 0.f && roofDepth > 0.3f && rep.sinkTime < 0.f) rep.sinkTime = q.t - tIn;
                  return rep.sinkTime > 0.f && q.t - tIn > rep.sinkTime + 1.f;
              });
    }
    // ---- dt jitter ----
    ScenarioTrace st_jitter(r, "jitter");
    {
        Rng rng(7);
        r.jitter = &rng;
        r.init(m, kPadStart + vec3(0, 20.f, 0), -kHalfPi);
        rep.jitterT100 = accelTo(r, 27.78f, 40.f);
        r.run(3.f, [](VehicleControls& c, Runner&) { c.steer = 1.f; c.throttle = 1.f; }, [](Runner&) { return false; });
        r.jitter = nullptr;
    }
    // ---- sleep + perf ----
    ScenarioTrace st_perf(r, "perf");
    {
        r.init(m, vec3(-3500.f, 50.f, 0.f), 0.3f);
        rep.sleepTime = r.run(5.f, [](VehicleControls& c, Runner&) { c.handbrake = true; c.brake = 1.f; }, [](Runner& q) { return q.s.sleeping; });
        r.stepUs = 0;
        r.steps = 0;
        r.run(1.f, [](VehicleControls& c, Runner&) { c.handbrake = true; c.brake = 1.f; }, [](Runner&) { return false; });
        rep.usSleep = r.stepUs / Max(r.steps, 1L);
        // driving perf: circle at 20 m/s
        r.init(m, vec3(-2500.f, 50.f, 0.f), -kHalfPi);
        accelTo(r, 15.f, 20.f);
        r.stepUs = 0;
        r.steps = 0;
        r.run(10.f, [](VehicleControls& c, Runner& q) { c.steer = 0.4f; holdSpeed(c, q, 15.f); }, [](Runner&) { return false; });
        rep.usPerStep = r.stepUs / Max(r.steps, 1L);
    }
    // ---- bikes: lean vs speed, wheelie, stoppie, crash, parking ----
    ScenarioTrace st_bike(r, "bike");
    if (bike) {
        auto leanAt = [&](float v, float& radius) {
            r.init(m, vec3(-3000.f, 0.f, 0.f), -kHalfPi);
            accelTo(r, v, 30.f);
            float leanAcc = 0.f, radAcc = 0.f;
            int n = 0;
            float t0 = r.t;
            r.run(5.f, [&](VehicleControls& c, Runner& q) { c.steer = 1.f; holdSpeed(c, q, v); },
                  [&](Runner& q) {
                      if (q.t - t0 > 3.f) {
                          leanAcc += q.roll();
                          radAcc += q.s.speed() / Max(fabsf(q.s.body.angVel.z), 1e-3f);
                          n++;
                      }
                      return false;
                  });
            radius = n ? radAcc / n : 0.f;
            return n ? leanAcc / n * kRadToDeg : 0.f;
        };
        float rad;
        rep.lean10 = leanAt(10.f, rad);
        rep.lean20 = leanAt(20.f, rad);
        rep.radius20 = rad;
        rep.lean30 = m.topSpeed > 32.f ? leanAt(30.f, rad) : 0.f;
        // full lock under full throttle from 7 m/s (a tight intersection taken too hot): the lean must stay bounded
        {
            ScenarioTrace st_lock(r, "bike_lock");
            r.init(m, vec3(-3000.f, 0.f, 0.f), -kHalfPi);
            accelTo(r, 7.f, 20.f);
            float lMax = 0.f;
            bool down = false;
            r.run(6.f, [](VehicleControls& c, Runner&) { c.steer = 1.f; c.throttle = 1.f; },
                  [&](Runner& q) {
                      lMax = Max(lMax, fabsf(q.roll()));
                      down = down || q.s.riderOff;
                      return false;
                  });
            rep.lockLean = down ? -lMax * kRadToDeg : lMax * kRadToDeg;
        }
        // wheelie: from 6 m/s, full throttle + lean back
        r.init(m, kPadStart, -kHalfPi);
        accelTo(r, 6.f, 10.f);
        float pMax = 0.f, tW = 0.f;
        r.run(6.f, [](VehicleControls& c, Runner&) { c.throttle = 1.f; c.pitch = 1.f; },
              [&](Runner& q) {
                  pMax = Max(pMax, q.pitch());
                  if (!q.s.wheels[0].contact && q.s.wheels[1].contact) tW += 1.f / 120.f;
                  return false;
              });
        rep.wheelieMax = pMax * kRadToDeg;
        rep.wheelieTime = tW;
        // stoppie from 15 m/s
        r.init(m, kPadStart, -kHalfPi);
        accelTo(r, 15.f, 20.f);
        pMax = 0.f;
        r.run(4.f, [](VehicleControls& c, Runner&) { c.brake = 1.f; c.pitch = -1.f; }, [&](Runner& q) {
            pMax = Min(pMax, q.pitch());
            return q.s.speed() < 0.5f;
        });
        rep.stoppieMax = pMax * kRadToDeg;
        // crash into the wall at 15 m/s: rider ejected
        r.init(m, vec3(1900.f, 20.f, 0.f), -kHalfPi);
        bool ej = false;
        r.run(15.f, [](VehicleControls& c, Runner& q) { holdSpeed(c, q, 15.f); }, [&](Runner& q) {
            ej = ej || q.s.ejectRider;
            return ej;
        });
        rep.crashEject = ej ? 1.f : 0.f;
        // parked, no rider: rests on the kickstand
        r.init(m, vec3(-3000.f, -50.f, 0.f), 0.f);
        r.run(5.f, [](VehicleControls& c, Runner&) { c.hasDriver = false; c.handbrake = true; c.brake = 1.f; }, [](Runner&) { return false; });
        rep.parkedLean = r.roll() * kRadToDeg;
    }
}


// Metadata audit: prints the physics-relevant metadata of each model and flags values that produce bad handling.
void auditModel(const VehicleModel& m) {
    VehicleState st;
    initVehicle(st, m, 0, dvec3(-3000, 0, 0), 0.f);
    const VehicleTuning& t = st.tune;
    fprintf(gOut, "| %s | %s | %.0f | %.0f | %.0f | %.0f | %.1f | %d | %.2f | %.0f | %.2f | %.2f/%.2f | %.2f/%.2f/%.1f | (%.2f,%.2f,%.2f) | (%.2f,%.2f,%.2f)+-(%.2f,%.2f,%.2f) | %d | %.1f/%.1f/%.1f |\n",
            m.name.c_str(), className(m.cls), m.mass, m.power, m.torque, m.maxRpm, m.topSpeed, m.gears, m.driveFront, m.brakeForce,
            m.grip, m.suspensionTravel, m.suspensionStiffness, m.dragCoef, m.frontalArea, m.downforce, m.centerOfMass.x,
            m.centerOfMass.y, m.centerOfMass.z, m.boxCenter.x, m.boxCenter.y, m.boxCenter.z, m.boxHalf.x, m.boxHalf.y, m.boxHalf.z,
            (int)m.wheels.size(), m.wingArea, m.liftSlope, m.rotorRadius);
    // checks
    float zb = m.boxCenter.z - m.boxHalf.z;
    if (m.boxHalf.x < 0.1f || m.boxHalf.y < 0.1f || m.boxHalf.z < 0.1f) issue("%s: collision box missing/degenerate (boxHalf %.2f %.2f %.2f)", m.name.c_str(), m.boxHalf.x, m.boxHalf.y, m.boxHalf.z);
    vec3 cl = m.centerOfMass - m.boxCenter;
    if (fabsf(cl.x) > m.boxHalf.x || fabsf(cl.y) > m.boxHalf.y || fabsf(cl.z) > m.boxHalf.z + 0.3f)
        issue("%s: centerOfMass (%.2f %.2f %.2f) outside the collision box", m.name.c_str(), m.centerOfMass.x, m.centerOfMass.y, m.centerOfMass.z);
    bool wheeled = m.cls <= VC_SCOOTER;
    if (wheeled && m.wheels.size() < 2) issue("%s: road vehicle without wheels", m.name.c_str());
    int driven = 0, steered = 0;
    for (auto& w : m.wheels) {
        driven += w.drive;
        steered += w.steer;
        if (fabsf(w.pos.z - w.radius) > 0.03f && m.cls != VC_PLANE && m.cls != VC_HELI)
            issue("%s: wheel at z=%.2f with radius %.2f (expected z == radius so the origin is the ground plane at rest)", m.name.c_str(), w.pos.z, w.radius);
        if (zb < w.pos.z - w.radius + 0.06f && wheeled && m.cls != VC_MOTORBIKE && m.cls != VC_SCOOTER)
            issue("%s: collision box bottom (%.2f) almost at ground level: chassis will scrape", m.name.c_str(), zb);
    }
    if (wheeled && driven == 0) issue("%s: no driven wheel", m.name.c_str());
    if (wheeled && steered == 0) issue("%s: no steered wheel", m.name.c_str());
    if (wheeled) {
        float wMax = m.maxRpm * kTwoPi / 60.f;
        float pAtRed = m.torque * wMax;
        if (pAtRed < m.power * 1000.f * 0.8f) issue("%s: torque %.0f Nm cannot produce %.0f kW below %.0f rpm (sim raises the peak torque to %.0f Nm)", m.name.c_str(), m.torque, m.power, m.maxRpm, t.peakTorque);
        // power-limited top speed
        float cda = m.dragCoef * m.frontalArea;
        float vPow = cbrtf(m.power * 1000.f * 0.9f / (0.5f * 1.225f * Max(cda, 0.05f)));
        if (vPow < m.topSpeed * 0.93f) issue("%s: topSpeed %.0f km/h but power/drag only allow ~%.0f km/h", m.name.c_str(), m.topSpeed * 3.6f, vPow * 3.6f);
        float drivenFront = 0.f;
        for (auto& w : m.wheels) if (w.drive && w.pos.y > m.centerOfMass.y) drivenFront += 1.f;
        if (drivenFront > 0.f && m.driveFront <= 0.f && driven > drivenFront) issue("%s: front wheels flagged drive but driveFront = 0 (sim treats it as RWD)", m.name.c_str());
    }
}


// ---------------------------------------------------------------------------------------------------------------
// Boats
struct BoatReport {
    std::string name;
    VehicleClass cls;
    float t50 = -1, topSpeed = 0, humpPitch = 0, humpSpeed = 0, planeSpeed = -1, turnDiam = -1, turnRoll = 0;
    float heaveIdle = 0, pitchIdle = 0, rollIdle = 0, heaveRun = 0, pitchRun = 0;
    float beachStop = -1, beachUpright = 0, mudSpeed = -1, drift = 0, capsized = 0;
    double usPerStep = 0;
};

void testBoat(const VehicleModel& m, BoatReport& rep) {
    Runner r;
    Phys::gWaves.strength = 0.3f;
    Phys::gWaves.time = 0.f;
    // ---- acceleration, planing, top speed ----
    ScenarioTrace st_acc(r, "boat_accel");
    r.init(m, vec3(3700.f, -1000.f, 0.f), -kHalfPi);
    float vTop = 0.f, pMax = 0.f, pMaxV = 0.f;
    bool planed = false;
    r.stepUs = 0;
    r.steps = 0;
    r.run(70.f,
          [&](VehicleControls& c, Runner& q) {
              c.throttle = 1.f;
              c.steer = steerTo(q, vec2(q.pos().x + 50.f, -1000.f), 1.f);
              Phys::gWaves.time = q.t;
          },
          [&](Runner& q) {
              float v = q.s.forwardSpeed();
              if (rep.t50 < 0.f && v > 13.9f) rep.t50 = q.t;
              vTop = Max(vTop, v);
              float p = q.pitch() * kRadToDeg;
              if (p > pMax) {
                  pMax = p;
                  pMaxV = v;
              }
              if (!planed && pMax > 2.f && p < pMax * 0.5f && v > pMaxV) {
                  planed = true;
                  rep.planeSpeed = v;
              }
              return q.pos().x > 6300.f;
          });
    rep.usPerStep = r.stepUs / Max(r.steps, 1L);
    rep.topSpeed = vTop;
    rep.humpPitch = pMax;
    rep.humpSpeed = pMaxV;
    // ---- turning circle at full throttle, full right ----
    ScenarioTrace st_turn(r, "boat_turn");
    r.init(m, vec3(5000.f, 0.f, 0.f), -kHalfPi);
    r.run(15.f, [&](VehicleControls& c, Runner& q) { c.throttle = 1.f; Phys::gWaves.time = q.t; }, [](Runner&) { return false; });
    float h0 = r.heading();
    vec2 mn(1e9f), mx(-1e9f);
    float turned = 0.f, lastH = h0, rollAcc = 0.f;
    int rn = 0;
    r.run(60.f,
          [&](VehicleControls& c, Runner& q) {
              c.throttle = 1.f;
              c.steer = 1.f;
              Phys::gWaves.time = q.t;
          },
          [&](Runner& q) {
              float h = q.heading();
              turned += fabsf(wrapPi(h - lastH));
              lastH = h;
              if (turned > kPi) {
                  mn = vmin(mn, q.pos().xy());
                  mx = vmax(mx, q.pos().xy());
                  rollAcc += q.roll();
                  rn++;
              }
              if (q.s.up().z < 0.3f) rep.capsized = 1.f;
              return turned > 3.f * kPi;
          });
    rep.turnDiam = 0.5f * ((mx.x - mn.x) + (mx.y - mn.y));
    rep.turnRoll = rn ? rollAcc / rn * kRadToDeg : 0.f;
    // ---- wave riding: strong waves, idle then 15 m/s ----
    ScenarioTrace st_wave(r, "boat_waves");
    Phys::gWaves.strength = 1.0f;
    r.init(m, vec3(5000.f, -500.f, 0.f), 0.f);
    auto stats = [&](float dur, float speed, float& heave, float& pitch, float& roll) {
        double sz = 0, szz = 0, sp = 0, spp = 0, sr = 0, srr = 0;
        int n = 0;
        float t0 = r.t;
        r.run(dur,
              [&](VehicleControls& c, Runner& q) {
                  if (speed > 0.f) holdSpeed(c, q, speed);
                  Phys::gWaves.time = q.t;
              },
              [&](Runner& q) {
                  if (q.t - t0 < 5.f) return false;
                  float z = (float)q.s.body.pos.z, p = q.pitch(), rr = q.roll();
                  sz += z; szz += z * z; sp += p; spp += p * p; sr += rr; srr += rr * rr;
                  n++;
                  return false;
              });
        heave = (float)sqrt(Max(szz / n - Sq(sz / n), 0.0));
        pitch = (float)sqrt(Max(spp / n - Sq(sp / n), 0.0)) * kRadToDeg;
        roll = (float)sqrt(Max(srr / n - Sq(sr / n), 0.0)) * kRadToDeg;
    };
    stats(25.f, 0.f, rep.heaveIdle, rep.pitchIdle, rep.rollIdle);
    float dummy;
    stats(25.f, 15.f, rep.heaveRun, rep.pitchRun, dummy);
    Phys::gWaves.strength = 0.3f;
    // ---- beaching: 10 m/s toward the west shore ----
    ScenarioTrace st_beach(r, "boat_beach");
    r.init(m, vec3(3350.f, 800.f, 0.f), kHalfPi);  // heading -x toward the beach at x ~ 3100
    float tb = r.run(40.f,
                     [&](VehicleControls& c, Runner& q) {
                         if (q.pos().x > 3120.f) holdSpeed(c, q, 10.f);
                         Phys::gWaves.time = q.t;
                     },
                     [&](Runner& q) { return q.pos().x < 3140.f && q.s.speed() < 0.3f; });
    rep.beachStop = tb;
    rep.beachUpright = r.s.up().z;
    // ---- airboat: lake -> shallow mud water -> dry mud ----
    if (m.cls == VC_AIRBOAT) {
        ScenarioTrace st_mud(r, "boat_mud");
        r.init(m, vec3(4000.f, 1400.f, 0.f), 0.f);  // heading +y
        float vAcc = 0.f;
        int n = 0;
        r.run(90.f,
              [&](VehicleControls& c, Runner& q) {
                  c.throttle = 1.f;
                  c.steer = steerTo(q, vec2(4000.f, q.pos().y + 40.f), 1.f);
                  Phys::gWaves.time = q.t;
              },
              [&](Runner& q) {
                  if (q.pos().y > 2750.f && q.pos().y < 3300.f) {
                      vAcc += q.s.speed();
                      n++;
                  }
                  return q.pos().y > 3300.f;
              });
        rep.mudSpeed = n ? vAcc / n : 0.f;
    }
    // ---- drift with no input (wind/waves) ----
    Phys::gWaves.strength = 0.3f;
}

void printBoatTable(const std::vector<BoatReport>& reps) {
    fprintf(gOut, "\n### Boats (lake, waves strength 0.3; wave test 1.0)\n\n");
    fprintf(gOut, "| model | class | 0-50 km/h s | top km/h | hump pitch deg @ m/s | planing at m/s | turn circle m | turn bank deg | idle heave m / pitch / roll deg | 15 m/s heave m / pitch deg | beach stop s / upright | dry mud km/h | capsized | us/step |\n");
    fprintf(gOut, "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n");
    for (auto& r : reps)
        fprintf(gOut, "| %s | %s | %.1f | %.0f | %.1f @ %.1f | %.1f | %.0f | %.1f | %.2f / %.1f / %.1f | %.2f / %.1f | %.1f / %.2f | %.0f | %s | %.1f |\n", r.name.c_str(),
                className(r.cls), r.t50, r.topSpeed * 3.6f, r.humpPitch, r.humpSpeed, r.planeSpeed, r.turnDiam, r.turnRoll, r.heaveIdle,
                r.pitchIdle, r.rollIdle, r.heaveRun, r.pitchRun, r.beachStop, r.beachUpright, r.mudSpeed * 3.6f, r.capsized > 0 ? "YES" : "no",
                r.usPerStep);
}

// ---------------------------------------------------------------------------------------------------------------
// Aircraft
struct AirReport {
    std::string name;
    VehicleClass cls;
    // plane
    float toSpeed = -1, toDist = -1, climb = 0, gearUpAlt = -1, topSpeed = 0, stallSpeed = -1, stallLoss = -1, turnRate = 0;
    // heli
    float spool = -1, hoverDrift = -1, hoverAlt = -1, climbRate = 0, maxSpeed = 0, landed = 0, strike = 0;
    double usPerStep = 0;
};

// altitude/vertical speed hold via elevator (planes)
float pitchForVz(Runner& q, float vzTarget, float& integ) {
    float vz = q.s.body.vel.z;
    float e = vzTarget - vz;
    integ = Clamp(integ + e * 0.02f / 120.f * 60.f, -0.6f, 0.6f);
    float pr = q.s.body.angVel.x * q.s.right().x + q.s.body.angVel.y * q.s.right().y;
    return Clamp(0.08f * e + integ - 0.3f * pr, -1.f, 1.f);
}
float rollForBank(Runner& q, float bankTarget) {
    float e = bankTarget - q.roll();
    return Clamp(e * 2.f - dot(q.s.body.angVel, q.s.forward()) * 0.6f, -1.f, 1.f);
}

void testPlane(const VehicleModel& m, AirReport& rep) {
    Runner r;
    // ---- takeoff roll ----
    ScenarioTrace st_to(r, "plane_takeoff");
    r.init(m, vec3(-4500.f, 0.f, 0.f), -kHalfPi);
    vec3 p0 = r.pos();
    float tAir = -1.f;
    r.stepUs = 0;
    r.steps = 0;
    float vRot = 0.f;
    {
        // rotation speed ~1.15x the clean stall speed estimate
        float S = m.wingArea > 0.5f ? m.wingArea : m.mass / 75.f;
        float vs = sqrtf(2.f * m.mass * 9.81f / (1.225f * S * 1.4f));
        vRot = 1.1f * vs;
    }
    r.run(90.f,
          [&](VehicleControls& c, Runner& q) {
              c.throttle = 1.f;
              c.steer = steerTo(q, vec2(q.pos().x + 100.f, 0.f), 1.f);
              if (q.s.forwardSpeed() > vRot) c.pitch = q.pitch() < 0.17f ? 0.7f : 0.2f;
          },
          [&](Runner& q) {
              bool air = true;
              for (int i = 0; i < q.s.wheelCount; i++) air = air && !q.s.wheels[i].contact;
              if (air && tAir < 0.f) {
                  tAir = q.t;
                  rep.toSpeed = q.s.speed();
                  rep.toDist = length(q.pos().xy() - p0.xy());
              }
              if (!air) tAir = -1.f;
              return tAir > 0.f && q.t - tAir > 1.f;
          });
    // ---- climb at full throttle holding ~8 degrees pitch; gear retraction ----
    ScenarioTrace st_climb(r, "plane_climb");
    float vzAcc = 0.f;
    int n = 0;
    float t0 = r.t;
    r.run(40.f,
          [&](VehicleControls& c, Runner& q) {
              c.throttle = 1.f;
              float pe = 0.14f - q.pitch();
              c.pitch = Clamp(pe * 3.f - q.s.body.angVel.x * 0.f, -1.f, 1.f);
              c.roll = rollForBank(q, 0.f);
          },
          [&](Runner& q) {
              if (rep.gearUpAlt < 0.f && q.s.gearDown < 0.05f) rep.gearUpAlt = q.s.agl;
              if (q.t - t0 > 20.f) {
                  vzAcc += q.s.body.vel.z;
                  n++;
              }
              return false;
          });
    rep.climb = n ? vzAcc / n : 0.f;
    // ---- turn south (heading hold) and climb to 400 m over land ----
    ScenarioTrace st_nav(r, "plane_nav");
    float integ = 0.f;
    const float hdgSouth = -kHalfPi;
    auto headingBank = [&](Runner& q, float hdg) {
        float e = wrapPi(hdg - q.heading());  // + = target to the left
        return Clamp(-e * 1.2f, -0.5f, 0.5f);
    };
    r.run(240.f,
          [&](VehicleControls& c, Runner& q) {
              c.throttle = 1.f;
              c.roll = rollForBank(q, headingBank(q, hdgSouth));
              c.pitch = pitchForVz(q, (float)q.s.body.pos.z < 400.f ? 3.f : 0.f, integ);
          },
          [&](Runner& q) { return q.s.body.pos.z > 400.0 && fabsf(wrapPi(hdgSouth - q.heading())) < 0.05f; });
    // ---- level top speed (altitude hold) ----
    ScenarioTrace st_top(r, "plane_top");
    float vTop = 0.f;
    float zHold = (float)r.s.body.pos.z;
    r.run(80.f,
          [&](VehicleControls& c, Runner& q) {
              c.throttle = 1.f;
              c.pitch = pitchForVz(q, Clamp((zHold - (float)q.s.body.pos.z) * 0.1f, -5.f, 5.f), integ);
              c.roll = rollForBank(q, headingBank(q, hdgSouth));
          },
          [&](Runner& q) {
              vTop = Max(vTop, q.s.speed());
              return false;
          });
    rep.topSpeed = r.s.speed();
    // ---- coordinated turn without rudder: 30 degree bank ----
    ScenarioTrace st_turnp(r, "plane_turn");
    float hh = r.heading();
    r.run(10.f,
          [&](VehicleControls& c, Runner& q) {
              c.throttle = 1.f;
              c.roll = rollForBank(q, 0.52f);
              c.pitch = pitchForVz(q, 0.f, integ);
          },
          [](Runner&) { return false; });
    rep.turnRate = fabsf(wrapPi(r.heading() - hh)) / 10.f * kRadToDeg;
    // ---- stall: throttle idle, hold altitude until the wing lets go ----
    ScenarioTrace st_stall(r, "plane_stall");
    zHold = (float)r.s.body.pos.z;
    float zStall = 0.f;
    float ts = r.run(120.f,
                     [&](VehicleControls& c, Runner& q) {
                         c.throttle = 0.f;
                         c.pitch = pitchForVz(q, Clamp((zHold - (float)q.s.body.pos.z) * 0.2f, -3.f, 3.f), integ);
                         c.roll = rollForBank(q, headingBank(q, hdgSouth));
                     },
                     [&](Runner& q) {
                         if (q.s.stall > 0.5f || (float)q.s.body.pos.z < zHold - 15.f) {
                             rep.stallSpeed = q.s.speed();
                             zStall = (float)q.s.body.pos.z;
                             return true;
                         }
                         return false;
                     });
    if (ts > 0.f) {
        // recovery: release the stick, full throttle; altitude lost until climbing again
        float zMin = zStall;
        r.run(30.f,
              [&](VehicleControls& c, Runner& q) {
                  c.throttle = 1.f;
                  c.roll = rollForBank(q, 0.f);
                  if (q.s.stall < 0.1f && q.s.speed() > rep.stallSpeed * 1.15f) c.pitch = 0.7f;
              },
              [&](Runner& q) {
                  zMin = Min(zMin, (float)q.s.body.pos.z);
                  return q.s.body.vel.z > 1.f && q.s.stall < 0.1f;
              });
        rep.stallLoss = zStall - zMin;
    }
    rep.usPerStep = r.stepUs / Max(r.steps, 1L);
}

void testHeli(const VehicleModel& m, AirReport& rep) {
    gPG->resetColliders();
    Runner r;
    r.init(m, vec3(-3000.f, 300.f, 0.f), 0.f);
    r.stepUs = 0;
    r.steps = 0;
    // ---- spool-up (engine on, no collective) ----
    ScenarioTrace st_sp(r, "heli_spool");
    rep.spool = r.run(30.f, [](VehicleControls&, Runner&) {}, [](Runner& q) { return q.s.rotorSpeed > 0.98f; });
    // ---- climb at full collective ----
    ScenarioTrace st_cl(r, "heli_climb");
    float vzMax = 0.f;
    r.run(15.f, [](VehicleControls& c, Runner&) { c.lift = 1.f; }, [&](Runner& q) {
        vzMax = Max(vzMax, q.s.body.vel.z);
        return q.s.body.pos.z > 40.0;
    });
    rep.climbRate = vzMax;
    // ---- hover: zero input for 3 s to settle, then 10 s drift ----
    ScenarioTrace st_hv(r, "heli_hover");
    r.run(3.f, [](VehicleControls&, Runner&) {}, [](Runner&) { return false; });
    vec3 p0 = r.pos();
    float maxD = 0.f;
    r.run(10.f, [](VehicleControls&, Runner&) {}, [&](Runner& q) {
        maxD = Max(maxD, length(q.pos() - p0));
        return false;
    });
    rep.hoverDrift = maxD;
    rep.hoverAlt = r.s.agl;
    // ---- max speed: full forward cyclic with altitude hold ----
    ScenarioTrace st_mx(r, "heli_speed");
    float zHold = (float)r.s.body.pos.z, vTop = 0.f;
    r.run(40.f,
          [&](VehicleControls& c, Runner& q) {
              c.pitch = -1.f;
              c.lift = Clamp(((zHold - (float)q.s.body.pos.z) * 0.3f - q.s.body.vel.z * 0.5f), -1.f, 1.f);
          },
          [&](Runner& q) {
              vTop = Max(vTop, sqrtf(Sq(q.s.body.vel.x) + Sq(q.s.body.vel.y)));
              return false;
          });
    rep.maxSpeed = vTop;
    // ---- stop, descend and land ----
    ScenarioTrace st_ld(r, "heli_land");
    r.run(15.f, [](VehicleControls&, Runner&) {}, [](Runner&) { return false; });
    float tl = r.run(40.f, [](VehicleControls& c, Runner&) { c.lift = -0.6f; }, [](Runner& q) { return q.s.agl < 0.3f && q.s.speed() < 0.2f; });
    r.run(3.f, [](VehicleControls&, Runner&) {}, [](Runner&) { return false; });
    rep.landed = (tl > 0.f && r.s.up().z > 0.95f) ? 1.f : 0.f;
    rep.usPerStep = r.stepUs / Max(r.steps, 1L);
    // ---- rotor strike: hover next to the tower and drift into it ----
    ScenarioTrace st_rs(r, "heli_strike");
    r.init(m, vec3(-2000.f, 370.f, 0.f), 0.f);
    r.s.rotorSpeed = 1.f;
    r.run(6.f, [](VehicleControls& c, Runner& q) { c.lift = q.s.body.pos.z < 25.0 ? 1.f : 0.f; }, [](Runner&) { return false; });
    bool hit = false;
    r.run(15.f, [](VehicleControls& c, Runner&) { c.pitch = -0.5f; }, [&](Runner& q) {
        hit = hit || q.s.rotorStrike;
        return hit;
    });
    rep.strike = hit ? 1.f : 0.f;
}

void printAirTable(const std::vector<AirReport>& reps) {
    fprintf(gOut, "\n### Planes\n\n| model | takeoff km/h | takeoff roll m | climb m/s | gear up at m AGL | top km/h (level) | turn deg/s (30 deg bank, no rudder) | stall km/h | stall recovery loss m | us/step |\n|---|---|---|---|---|---|---|---|---|---|\n");
    for (auto& r : reps)
        if (r.cls == VC_PLANE)
            fprintf(gOut, "| %s | %.0f | %.0f | %.1f | %.0f | %.0f | %.1f | %.0f | %.0f | %.1f |\n", r.name.c_str(), r.toSpeed * 3.6f, r.toDist, r.climb,
                    r.gearUpAlt, r.topSpeed * 3.6f, r.turnRate, r.stallSpeed * 3.6f, r.stallLoss, r.usPerStep);
    fprintf(gOut, "\n### Helicopters\n\n| model | spool-up s | climb m/s | hover drift m (10 s, no input) | hover AGL m | max speed km/h | lands upright | rotor strike | us/step |\n|---|---|---|---|---|---|---|---|---|\n");
    for (auto& r : reps)
        if (r.cls == VC_HELI)
            fprintf(gOut, "| %s | %.1f | %.1f | %.2f | %.0f | %.0f | %s | %s | %.1f |\n", r.name.c_str(), r.spool, r.climbRate, r.hoverDrift, r.hoverAlt,
                    r.maxSpeed * 3.6f, r.landed > 0 ? "yes" : "NO", r.strike > 0 ? "yes" : "no", r.usPerStep);
}


// ---------------------------------------------------------------------------------------------------------------
// Real world: long random drives on the generated road graph with streamed collision, building + curb checks
void testReal(RealWorld& rw, const VehicleModel& m, RealReport& rep, u32 seed, float routeLen) {
    Rng rng(seed);
    Route route;
    bool bike = m.cls == VC_MOTORBIKE || m.cls == VC_SCOOTER;
    route.build(rw.roads, rng, routeLen, true);
    if (route.pts.size() < 3 || route.totalLen < 300.f) return;
    Runner r;
    ScenarioTrace st(r, "real_drive");
    vec3 p0 = route.pts[0];
    vec2 d0 = normalize(route.pts[2].xy() - p0.xy());
    auto yawOf = [](vec2 d) { return atan2f(-d.x, d.y); };  // yaw 0 = +Y, positive CCW
    rw.ensureCells(p0.xy());
    r.init(m, p0 + vec3(0, 0, 0.3f), yawOf(d0));
    int idx = 0;
    float sNow = 0.f, stuckT = 0.f, driven = 0.f, bridgeDist = 0.f, tDrive = 0.f, lastSupportZ = -1e9f;
    vec3 lastP = r.pos();
    r.stepUs = 0;
    r.steps = 0;
    int stepCount = 0;
    auto respawnAhead = [&](float ahead) {
        float s2 = Min(sNow + ahead, route.totalLen - 1.f);
        vec3 p = route.at(s2);
        vec2 d = normalize(route.at(s2 + 3.f).xy() - p.xy());
        rw.ensureCells(p.xy());
        resetVehicle(r.s, dvec3(p + vec3(0, 0, 0.3f)), yawOf(d));
        idx = route.advance(p.xy(), idx);
        sNow = s2;
        lastP = r.pos();
    };
    float tMax = routeLen / 8.f + 60.f;
    r.run(tMax,
          [&](VehicleControls& c, Runner& q) {
              if (++stepCount % 60 == 0) rw.ensureCells(q.pos().xy());
              idx = route.advance(q.pos().xy(), idx);
              sNow = route.dist[idx];
              float v = q.s.speed();
              float look = 6.f + 0.45f * v;
              vec3 tgt = route.at(sNow + look);
              c.steer = steerTo(q, tgt.xy(), 1.6f);
              float lim = route.limit[idx] * 1.15f;
              float aLat = bike ? 4.5f : 5.5f;
              float vc = route.cornerSpeed(sNow, 20.f + v * 3.f, aLat);
              float vT = Min(Min(lim, vc), m.topSpeed * 0.85f);
              // still turning onto the new heading: the pure-pursuit arc to the look-ahead point bounds the speed
              {
                  vec2 dT = tgt.xy() - q.pos().xy();
                  float L = length(dT);
                  vec3 f = q.s.forward();
                  vec2 f2 = normalize(vec2(f.x, f.y) + vec2(1e-6f, 0.f));
                  float sa = L > 1e-3f ? fabsf(cross(f2, dT / L)) : 0.f;
                  if (sa > 0.05f) vT = Min(vT, Max(sqrtf(aLat * L / (2.f * sa)), 3.f));
              }
              holdSpeed(c, q, vT);
          },
          [&](Runner& q) {
              vec3 p = q.pos();
              float step = length(p.xy() - lastP.xy());
              lastP = p;
              if (step < 5.f) driven += step;
              if (route.bridge[idx]) bridgeDist += step;
              tDrive += 1.f / 120.f;
              rep.maxRoll = Max(rep.maxRoll, fabsf(q.roll()) * kRadToDeg);
              if (fabsf(q.pitch()) * kRadToDeg > 25.f && rep.maxPitch * kDegToRad < fabsf(q.pitch()))
                  printf("EVENT pitch %.0f deg at (%.1f %.1f %.1f) v=%.1f s=%.0f bridge=%d\n", q.pitch() * kRadToDeg, p.x, p.y, p.z, q.s.speed(), sNow, (int)route.bridge[idx]);
              rep.maxPitch = Max(rep.maxPitch, fabsf(q.pitch()) * kRadToDeg);
              if (q.s.impactImpulse > 5000.f && q.s.impactCollider >= 0) rep.impacts++;
              rep.broken += q.s.brokenCount;
              if (!std::isfinite(p.x)) {
                  rep.nans++;
                  respawnAhead(30.f);
                  return false;
              }
              // genuine fall-through: the surface that supported the car last step is now well above it
              {
                  Phys::GroundHit gNow = Phys::gCollision->ground(p.x, p.y, lastSupportZ + 0.3f, 0.f);
                  bool deckAbove = gNow.z > p.z + 1.0f && fabsf(gNow.z - lastSupportZ) < 0.3f;
                  if (deckAbove) {
                      printf("EVENT fell-through at (%.1f %.1f %.1f) surface %.1f v=%.1f vz=%.1f s=%.0f\n", p.x, p.y, p.z, gNow.z, q.s.speed(), q.s.body.vel.z, sNow);
                      rep.fellThrough++;
                      respawnAhead(40.f);
                      lastSupportZ = -1e9f;
                      return false;
                  }
                  Phys::GroundHit gBelow = Phys::gCollision->ground(p.x, p.y, p.z + 0.5f, 0.f);
                  lastSupportZ = q.s.wheelsOnGround > 0 ? gBelow.z : -1e9f;
              }
              // left an elevated road over an unguarded edge (world geometry), counted separately
              if (route.bridge[idx] && p.z < route.pts[idx].z - 2.5f) {
                  printf("EVENT off-deck at (%.1f %.1f %.1f) deck %.1f v=%.1f s=%.0f\n", p.x, p.y, p.z, route.pts[idx].z, q.s.speed(), sNow);
                  rep.offDeck++;
                  respawnAhead(40.f);
                  return false;
              }
              if (q.s.up().z < 0.3f && !bike) {
                  printf("EVENT flip at (%.1f %.1f %.1f) v=%.1f s=%.0f bridge=%d\n", p.x, p.y, p.z, q.s.speed(), sNow, (int)route.bridge[idx]);
                  rep.flips++;
                  respawnAhead(30.f);
                  return false;
              }
              if (bike && q.s.riderOff) {
                  printf("EVENT bike crash at (%.1f %.1f %.1f) v=%.1f lean=%.0f pitch=%.0f impact=%.0f/%d s=%.0f bridge=%d\n", p.x, p.y, p.z, q.s.speed(), q.s.lean * kRadToDeg,
                         q.pitch() * kRadToDeg, q.s.impactImpulse, q.s.impactCollider, sNow, (int)route.bridge[idx]);
                  rep.flips++;
                  respawnAhead(30.f);
                  return false;
              }
              stuckT = q.s.speed() < 0.5f ? stuckT + 1.f / 120.f : 0.f;
              if (stuckT > 4.f) {
                  // is the lane itself blocked by a world collider (building/garage/tree on the road)?
                  bool blocked = false;
                  {
                      std::vector<int> ids;
                      rw.cw.collidersNear(p.xy(), 8.f, ids);
                      for (int id : ids) {
                          const Phys::Collider& c = rw.cw.collider(id);
                          if (c.owner < 0 || c.he.x <= 0.f) continue;
                          for (float ahead = 0.f; ahead <= 8.f && !blocked; ahead += 1.f) {
                              vec3 lp = route.at(sNow + ahead);
                              vec2 dd = lp.xy() - c.c.xy();
                              if (c.kind == Phys::COL_BOX) {
                                  vec2 ay(-c.ax.y, c.ax.x);
                                  if (fabsf(dot(dd, c.ax)) < c.he.x + 0.8f && fabsf(dot(dd, ay)) < c.he.y + 0.8f && lp.z + 0.5f > c.c.z - c.he.z) blocked = true;
                              } else if (length(dd) < c.he.x + 0.8f) {
                                  blocked = true;
                              }
                          }
                      }
                  }
                  printf("EVENT stuck%s at (%.1f %.1f %.1f) route (%.1f %.1f %.1f) s=%.0f bridge=%d up=%.2f\n", blocked ? "(lane blocked by world collider)" : "", p.x, p.y, p.z,
                         route.pts[idx].x, route.pts[idx].y, route.pts[idx].z, sNow, (int)route.bridge[idx], q.s.up().z);
                  if (blocked) rep.blocked++;
                  else rep.stuck++;
                  stuckT = 0.f;
                  respawnAhead(30.f);
                  return false;
              }
              return sNow > route.totalLen - 30.f;
          });
    rep.km += driven / 1000.f;
    rep.bridgeKm += bridgeDist / 1000.f;
    rep.avgSpeed = tDrive > 0.f ? driven / tDrive : 0.f;
    rep.usPerStep = r.stepUs / Max(r.steps, 1L);
}

// Aim at a real building from 45 m at 60 km/h: must stop at the wall, not pass through.
void testRealBuilding(RealWorld& rw, const VehicleModel& m, RealReport& rep, u32 seed) {
    Rng rng(seed);
    for (int tries = 0; tries < 20000; tries++) {
        const World::Building& b = rw.bs.buildings[rng.next() % rw.bs.buildings.size()];
        if (b.height < 6.f || b.hx < 6.f) continue;
        vec2 start = b.c + b.front * (b.hy + 45.f);
        float rz;
        if (!rw.roads.surfaceHeight(start, &rz, 1e9f)) continue;
        // clear path (no other building between start and the facade)
        bool clear = true;
        for (float t = 0.f; t < 38.f; t += 2.f) {
            vec2 q = start - b.front * t;
            float top;
            if (rw.bs.pointInBuilding(q, 1.5f, &top)) clear = false;
        }
        if (!clear) continue;
        if (fabsf(rz - b.baseZ) > 1.5f) continue;
        rw.ensureCells(start);
        rw.ensureCells(b.c);
        // the approach must be drivable: no drops or steps on the way, and the first thing hit must be the building itself
        bool flat = true;
        float prevZ = rz;
        for (float t = 2.f; t < 44.f && flat; t += 2.f) {
            vec2 q = start - b.front * t;
            Phys::GroundHit g = rw.cw.ground(q.x, q.y, prevZ + 1.f, 0.f);
            if (fabsf(g.z - prevZ) > 0.3f || g.water) flat = false;
            prevZ = g.z;
        }
        if (!flat) continue;
        Phys::RayHit rh;
        vec3 ro(start, rz + 0.7f), rd(-b.front, 0.f);
        if (!rw.cw.raycast(ro, rd, 60.f, rh, false) || rh.collider < 0 || !(rw.cw.collider(rh.collider).flags & 2)) continue;
        Runner r;
        ScenarioTrace st(r, "real_building");
        vec2 d = -b.front;
        r.init(m, vec3(start, rz + 0.3f), atan2f(-d.x, d.y));
        float minSpeedAfter = 1e9f;
        bool hit = false;
        float tHit = 0.f;
        r.run(12.f,
              [&](VehicleControls& c, Runner& q) {
                  if (!hit) holdSpeed(c, q, 16.7f);
                  c.steer = hit ? 0.f : steerTo(q, b.c, 1.5f);
              },
              [&](Runner& q) {
                  if (!hit && q.s.impactImpulse > 3.f * m.mass && q.s.impactCollider >= 0 && rw.cw.collider(q.s.impactCollider).flags & 2) {
                      hit = true;
                      tHit = q.t;
                  }
                  if (hit) minSpeedAfter = Min(minSpeedAfter, q.s.speed());
                  return hit && q.t - tHit > 2.f;
              });
        rep.bldgStop = hit ? minSpeedAfter : -1.f;
        rep.bldgInside = rw.bs.pointInBuilding(r.pos().xy(), -0.5f) ? 1.f : 0.f;
        rep.bldgHealth = r.s.health;
        return;
    }
}

// Cross a real street with sidewalks at walking pace (curb up/down twice).
void testRealCurb(RealWorld& rw, const VehicleModel& m, RealReport& rep, u32 seed) {
    Rng rng(seed);
    for (int tries = 0; tries < 2000; tries++) {
        const World::RoadEdge& e = rw.roads.edges[rng.next() % rw.roads.edges.size()];
        if (e.sidewalk < 1.f || e.cls != World::RC_STREET || e.length < 60.f || (e.flags & (World::RF_BRIDGE | World::RF_ELEVATED))) continue;
        float sMid = e.length * 0.5f;
        vec3 c = e.posAt(sMid);
        vec3 tng = e.tangentAt(sMid);
        vec2 n(tng.y, -tng.x);
        float reach = e.halfWidth + e.sidewalk;
        vec2 a = c.xy() - n * (reach + 4.f), bpt = c.xy() + n * (reach + 4.f);
        bool clear = true;
        for (float t = 0.f; t <= 1.f; t += 0.05f)
            if (rw.bs.pointInBuilding(lerp(a, bpt, t), 3.f)) clear = false;
        if (!clear) continue;
        // no other road/intersection nearby (keep it a plain mid-block crossing)
        int ne = rw.roads.nearestEdge(a, 3.f);
        if (ne >= 0 && &rw.roads.edges[ne] != &e) continue;
        rw.ensureCells(c.xy());
        // keep the crossing line free of street furniture (a light pole stops a car at walking pace, as it should)
        bool furnitureFree = true;
        for (float lo = -1.5f; lo <= 1.51f && furnitureFree; lo += 0.25f) {
            vec2 side(-n.y, n.x);
            vec2 a2 = a + side * lo;
            float gz0 = rw.map.heightAt(a2.x, a2.y);
            Phys::RayHit rh;
            vec3 ro(a2, Max(gz0, c.z) + 0.5f), rd(n, 0.f);
            if (rw.cw.raycast(ro, rd, 2.f * (reach + 4.f) + 10.f, rh, false) && rh.collider >= 0) furnitureFree = false;
        }
        if (!furnitureFree) continue;
        Runner r;
        ScenarioTrace st(r, "real_curb");
        float gz = rw.map.heightAt(a.x, a.y);
        r.init(m, vec3(a, Max(gz, c.z) + 0.2f), atan2f(-n.x, n.y));
        float tc = r.run(25.f,
                         [&](VehicleControls& cc, Runner& q) {
                             holdSpeed(cc, q, 3.f);
                             cc.steer = steerTo(q, bpt + n * 10.f, 1.5f);
                         },
                         [&](Runner& q) { return dot(q.pos().xy() - c.xy(), n) > reach + 2.f; });
        rep.curbCrossed = tc;
        return;
    }
}

void printRealTable(const std::vector<RealReport>& reps) {
    fprintf(gOut, "\n### Real world (generated Palmera: random routes on the road graph, streamed LOD0 collision)\n\n");
    fprintf(gOut, "| model | class | km driven | avg km/h | bridge/elevated km | max roll deg | max pitch deg | flips/crashes | stuck (other) / lane blocked by world | prop/bldg impacts | props broken | fell through a surface | drove off a deck edge | NaN | building @60: min speed after / inside / health | curb crossing s | us/step |\n");
    fprintf(gOut, "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n");
    for (auto& r : reps)
        fprintf(gOut, "| %s | %s | %.1f | %.0f | %.2f | %.0f | %.0f | %d | %d / %d | %d | %d | %d | %d | %d | %.1f / %s / %.0f | %.1f | %.1f |\n", r.name.c_str(),
                className(r.cls), r.km, r.avgSpeed * 3.6f, r.bridgeKm, r.maxRoll, r.maxPitch, r.flips, r.stuck, r.blocked, r.impacts, r.broken, r.fellThrough,
                r.offDeck, r.nans, r.bldgStop, r.bldgInside > 0 ? "YES" : "no", r.bldgHealth, r.curbCrossed, r.usPerStep);
}

void printCarTable(const std::vector<CarReport>& reps) {
    fprintf(gOut, "\n### Road vehicles (proving ground)\n\n");
    fprintf(gOut, "| model | class | 0-100 s | top km/h | 100-0 m | lat g | lanechg beta deg | no spin | hb turn deg / s | jump pitch/roll deg | bounces | upright | wall rebound m/s | wall pen m | health/engine | roll deg | wheels lifted | rolled | curb 3/10 m/s dz | prop fast/dv/slow | roof rest / flip s | sink s / engine s | 60m/s tunnel | jitter 0-100 | sleep s | us/step | us sleep |\n");
    fprintf(gOut, "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n");
    for (auto& r : reps) {
        if (r.cls == VC_MOTORBIKE || r.cls == VC_SCOOTER) continue;
        fprintf(gOut, "| %s | %s | %.1f | %.0f | %.1f | %.2f | %.1f | %s | %.0f / %.1f | %.0f / %.0f | %.0f | %.2f | %.1f | %.2f | %.0f / %.0f | %.1f | %.0f | %s | %.2f / %.2f | %.0f / %.1f / %.0f | %s / %.1f | %.1f / %.1f | %s | %.1f | %.1f | %.1f | %.2f |\n",
                r.name.c_str(), className(r.cls), r.t100, r.topSpeed * 3.6f, r.brake100, r.latG, r.laneChangeBeta, r.laneOk > 0 ? "yes" : "NO",
                r.hb180, r.hbTime, r.jumpPitch, r.jumpRoll, r.jumpBounces, r.jumpUpright, r.wallRebound, r.wallPen, r.wallHealth, r.wallEngine,
                r.rollMax, r.rollLift, r.rolledOver > 0 ? "YES" : "no", r.curbSlow, r.curbAngle, r.propBrokeFast, r.propDv, r.propBrokeSlow,
                r.flipRest > 0 ? "yes" : "NO", r.flipBack, r.sinkTime, r.engineDeadTime, r.tunnel > 0 ? "YES" : "no", r.jitterT100, r.sleepTime,
                r.usPerStep, r.usSleep);
    }
}

void printBikeTable(const std::vector<CarReport>& reps) {
    fprintf(gOut, "\n### Bikes (proving ground)\n\n");
    fprintf(gOut, "| model | class | 0-100 s | top km/h | 100-0 m | lat g | lanechg beta | no spin | lean 10/20/30 m/s deg | full lock+throttle max lean deg (neg = crashed) | radius@20 m | wheelie deg / s | stoppie deg | wall eject | parked lean deg | jump pitch/roll | upright | curb dz | 60m/s tunnel | us/step |\n");
    fprintf(gOut, "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n");
    for (auto& r : reps) {
        if (r.cls != VC_MOTORBIKE && r.cls != VC_SCOOTER) continue;
        fprintf(gOut, "| %s | %s | %.1f | %.0f | %.1f | %.2f | %.1f | %s | %.0f / %.0f / %.0f | %.0f | %.0f | %.0f / %.1f | %.0f | %s | %.1f | %.0f / %.0f | %.2f | %.2f | %s | %.1f |\n",
                r.name.c_str(), className(r.cls), r.t100, r.topSpeed * 3.6f, r.brake100, r.latG, r.laneChangeBeta, r.laneOk > 0 ? "yes" : "NO",
                r.lean10, r.lean20, r.lean30, r.lockLean, r.radius20, r.wheelieMax, r.wheelieTime, r.stoppieMax, r.crashEject > 0 ? "yes" : "NO",
                r.parkedLean, r.jumpPitch, r.jumpRoll, r.jumpUpright, r.curbSlow, r.tunnel > 0 ? "YES" : "no", r.usPerStep);
    }
}

}  // namespace VT

int main(int argc, char** argv) {
    bool synthetic = true, real = false, useModels = false, audit = false;
    int realRoutes = 2;
    std::vector<vec3> probes;
    float realLen = 6000.f;
    const char* only = nullptr;
    const char* outPath = nullptr;
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--real")) real = true;
        else if (!strcmp(argv[i], "--models")) useModels = true;
        else if (!strcmp(argv[i], "--audit")) audit = true;
        else if (!strcmp(argv[i], "--routes") && i + 1 < argc) realRoutes = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--probe") && i + 1 < argc) {
            vec3 p;
            if (sscanf(argv[++i], "%f,%f,%f", &p.x, &p.y, &p.z) == 3) probes.push_back(p);
        }
        else if (!strcmp(argv[i], "--routelen") && i + 1 < argc) realLen = (float)atof(argv[++i]);
        else if (!strcmp(argv[i], "--class") && i + 1 < argc) only = argv[++i];
        else if (!strcmp(argv[i], "--out") && i + 1 < argc) outPath = argv[++i];
        else if (!strcmp(argv[i], "--nosynthetic")) synthetic = false;
        else if (!strcmp(argv[i], "--trace") && i + 1 < argc) gTrace = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--scenario") && i + 1 < argc) gTraceScenario = argv[++i];
        else if (!strcmp(argv[i], "--wheels")) gWheelTrace = true;
    }
    if (outPath) gOut = fopen(outPath, "w");
    Jobs::init(Max(1, (int)std::thread::hardware_concurrency() - 1));
    static ProvingGround pg;
    pg.build();
    gPG = &pg;
    std::vector<VehicleModel> models;
#ifdef HAVE_MODELS
    if (useModels) {
        int n = modelCount();
        models.resize(n);
        for (int i = 0; i < n; i++) buildModel(i, models[i]);
    }
#endif
    if (models.empty()) {
        for (int c = 0; c < VC_COUNT; c++) {
            VehicleClass cls = (VehicleClass)c;
            if (cls == VC_TAXI || cls == VC_AMBULANCE || cls == VC_FIRETRUCK || cls == VC_SERVICE) continue;
            models.push_back(makeTestModel(cls));
            models.back().name = std::string("std-") + className(cls);
        }
    }
    if (audit) {
        fprintf(gOut, "\n### Model metadata\n\n| model | class | kg | kW | Nm | rpm | top m/s | gears | driveF | brakeN | grip | travel/stiff | cd/A/down | com | box | wheels | wing/slope/rotor |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n");
        for (auto& m : models) auditModel(m);
    }
    if (synthetic) {
        std::vector<CarReport> cars;
        for (auto& m : models) {
            if (only && strcmp(only, className(m.cls)) && strcmp(only, m.name.c_str())) continue;
            if (m.cls >= VC_BOAT) continue;
            CarReport rep;
            rep.name = m.name;
            rep.cls = m.cls;
            testCar(m, rep);
            cars.push_back(rep);
            fprintf(stderr, "done %s\n", m.name.c_str());
        }
        printCarTable(cars);
        printBikeTable(cars);
        std::vector<BoatReport> boats;
        std::vector<AirReport> air;
        for (auto& m : models) {
            if (only && strcmp(only, className(m.cls)) && strcmp(only, m.name.c_str())) continue;
            if (m.cls == VC_BOAT || m.cls == VC_JETSKI || m.cls == VC_AIRBOAT) {
                BoatReport rep;
                rep.name = m.name;
                rep.cls = m.cls;
                testBoat(m, rep);
                boats.push_back(rep);
                fprintf(stderr, "done %s\n", m.name.c_str());
            } else if (m.cls == VC_PLANE || m.cls == VC_HELI) {
                AirReport rep;
                rep.name = m.name;
                rep.cls = m.cls;
                if (m.cls == VC_PLANE) testPlane(m, rep);
                else testHeli(m, rep);
                air.push_back(rep);
                fprintf(stderr, "done %s\n", m.name.c_str());
            }
        }
        if (!boats.empty()) printBoatTable(boats);
        if (!air.empty()) printAirTable(air);
    }
    if (real) {
        static RealWorld rw;
        rw.build();
        for (auto& pr : probes) {
            // ground profile + nearby road edges around a point
            printf("PROBE (%.1f %.1f) zref %.1f\n", pr.x, pr.y, pr.z);
            rw.ensureCells(pr.xy());
            {
                std::vector<int> ids;
                rw.cw.collidersNear(pr.xy(), 12.f, ids);
                for (int id : ids) {
                    const Phys::Collider& c = rw.cw.collider(id);
                    if (c.owner < 0) continue;
                    printf("  collider %d kind %d flags %d c=(%.1f %.1f %.1f) he=(%.2f %.2f %.2f) ax=(%.2f %.2f)\n", id, c.kind, c.flags, c.c.x, c.c.y, c.c.z,
                           c.he.x, c.he.y, c.he.z, c.ax.x, c.ax.y);
                }
            }
            std::vector<int> cand;
            rw.roads.edgesInRect(pr.xy() - vec2(30.f), pr.xy() + vec2(30.f), cand);
            for (int ei : cand) {
                const World::RoadEdge& e = rw.roads.edges[ei];
                float best = 1e9f, bz = 0.f;
                for (size_t k = 0; k + 1 < e.pts.size(); k++) {
                    float t;
                    float d = distPointSegment2D(pr.xy(), e.pts[k].xy(), e.pts[k + 1].xy(), &t);
                    if (d < best) { best = d; bz = Lerp(e.pts[k].z, e.pts[k + 1].z, t); }
                }
                printf("  edge %d cls %d flags %d hw %.1f sw %.1f dist %.1f z %.2f n0z %.2f(r%.1f) n1z %.2f(r%.1f)\n", ei, e.cls, e.flags, e.halfWidth, e.sidewalk, best, bz,
                       rw.roads.nodes[e.n0].z, rw.roads.nodes[e.n0].radius, rw.roads.nodes[e.n1].z, rw.roads.nodes[e.n1].radius);
            }
            for (int k = -10; k <= 10; k++) {
                for (int j = -10; j <= 10; j += 2) {
                    float gz;
                    bool on = rw.roads.surfaceHeight(pr.xy() + vec2(j * 2.f, k * 2.f), &gz, pr.z + 1.f);
                    Phys::GroundHit g = Phys::gCollision->ground(pr.x + j * 2.f, pr.y + k * 2.f, pr.z + 1.f, 0.f);
                    printf("%6.1f%c", g.z, on ? '*' : ' ');
                }
                printf("   y=%+d\n", k * 2);
            }
        }
        std::vector<RealReport> reps;
        for (size_t mi = 0; mi < models.size(); mi++) {
            const VehicleModel& m = models[mi];
            if (only && strcmp(only, className(m.cls)) && strcmp(only, m.name.c_str())) continue;
            if (m.cls >= VC_BOAT) continue;
            RealReport rep;
            rep.name = m.name;
            rep.cls = m.cls;
            // seeds depend on the model's catalog index so a --class run reproduces the full run
            for (int k = 0; k < realRoutes * 8 && rep.km < realRoutes * realLen / 1000.f; k++)
                testReal(rw, m, rep, 1234u + 77u * k + (u32)mi * 1000u, realLen);
            testRealBuilding(rw, m, rep, 99u + (u32)mi);
            testRealCurb(rw, m, rep, 555u + (u32)mi);
            reps.push_back(rep);
            fprintf(stderr, "real done %s (cells %.1f s)\n", m.name.c_str(), rw.cellGenSeconds);
        }
        printRealTable(reps);
    }
    if (!gIssues.empty()) {
        fprintf(gOut, "\n### Issues\n");
        for (auto& s : gIssues) fprintf(gOut, "- %s\n", s.c_str());
    }
    if (gOut != stdout) fclose(gOut);
    fflush(stdout);
    Jobs::shutdown();
    return 0;
}
