// Build-time tool: embeds every file in a directory into a C++ header as byte arrays.
// Usage: embed_shaders <input_dir> <output_header>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <algorithm>
#ifdef _WIN32
#include <windows.h>
#else
#include <dirent.h>
#endif

static std::vector<std::string> listFiles(const std::string& dir) {
    std::vector<std::string> out;
#ifdef _WIN32
    WIN32_FIND_DATAA fd;
    HANDLE h = FindFirstFileA((dir + "\\*").c_str(), &fd);
    if (h != INVALID_HANDLE_VALUE) {
        do {
            if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) out.push_back(fd.cFileName);
        } while (FindNextFileA(h, &fd));
        FindClose(h);
    }
#else
    DIR* d = opendir(dir.c_str());
    if (d) {
        while (dirent* e = readdir(d)) {
            if (e->d_name[0] == '.') continue;
            out.push_back(e->d_name);
        }
        closedir(d);
    }
#endif
    std::sort(out.begin(), out.end());
    return out;
}

int main(int argc, char** argv) {
    if (argc < 3) {
        fprintf(stderr, "usage: embed_shaders <dir> <out.h>\n");
        return 1;
    }
    std::string dir = argv[1];
    std::vector<std::string> files = listFiles(dir);
    std::string out;
    out += "// Generated by tools/embed_shaders.cpp - do not edit.\n#pragma once\n";
    out += "struct EmbeddedFile { const char* name; const char* data; unsigned size; };\n";
    int idx = 0;
    std::vector<std::string> names;
    for (auto& f : files) {
        std::string ext = f.substr(f.find_last_of('.') + 1);
        if (ext != "hlsl" && ext != "hlsli") continue;
        std::string path = dir + "/" + f;
        FILE* fp = fopen(path.c_str(), "rb");
        if (!fp) { fprintf(stderr, "cannot open %s\n", path.c_str()); return 1; }
        std::vector<unsigned char> data;
        unsigned char buf[65536];
        size_t n;
        while ((n = fread(buf, 1, sizeof(buf), fp)) > 0) data.insert(data.end(), buf, buf + n);
        fclose(fp);
        char hdr[128];
        snprintf(hdr, sizeof(hdr), "static const char s_embed%d[] = {", idx);
        out += hdr;
        for (size_t i = 0; i < data.size(); i++) {
            if (i % 24 == 0) out += "\n";
            char b[8];
            snprintf(b, sizeof(b), "%d,", (int)(signed char)data[i]);
            out += b;
        }
        out += "0};\n";
        names.push_back(f);
        idx++;
    }
    out += "static const EmbeddedFile g_embeddedShaders[] = {\n";
    for (int i = 0; i < idx; i++) {
        char line[512];
        snprintf(line, sizeof(line), "  {\"%s\", s_embed%d, (unsigned)sizeof(s_embed%d) - 1},\n", names[i].c_str(), i, i);
        out += line;
    }
    if (idx == 0) out += "  {\"\", \"\", 0},\n";
    out += "};\n";
    char cnt[64];
    snprintf(cnt, sizeof(cnt), "static const int g_embeddedShaderCount = %d;\n", idx);
    out += cnt;
    // Only rewrite when changed so incremental builds stay fast.
    FILE* old = fopen(argv[2], "rb");
    if (old) {
        std::string prev;
        char b2[65536];
        size_t n2;
        while ((n2 = fread(b2, 1, sizeof(b2), old)) > 0) prev.append(b2, n2);
        fclose(old);
        if (prev == out) return 0;
    }
    FILE* o = fopen(argv[2], "wb");
    if (!o) { fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
    fwrite(out.data(), 1, out.size(), o);
    fclose(o);
    printf("Embedded %d shader files.\n", idx);
    return 0;
}
