// Hand-written pronunciation dictionary: the most frequent English words plus vocabulary typical of a
// crime/action game (police radio, street talk, radio DJs and commercials) and the game's place names.
// Format: "word PHONEMES" with ARPAbet phonemes and stress digits (1 primary, 2 secondary, 0 none).
// A leading '~' on the pronunciation marks an unaccented function word.
// Regular inflections (-s, -ed, -ing, -er, -est, -ly, -ness, ...) are derived by the morphology in
// speech_rules.cpp, so mostly base forms and irregular forms are listed here.
#include "speech_internal.h"
#include <unordered_map>

namespace Speech {
namespace detail {

static const char* const kDictEntries[] = {
    // ---- articles, determiners, quantifiers
    "a ~AH0", "an ~AH0 N", "the ~DH AH0", "this ~DH IH0 S", "that ~DH AE0 T", "these ~DH IY0 Z", "those ~DH OW0 Z",
    "some ~S AH0 M", "any EH1 N IY0", "every EH1 V R IY0", "each IY1 CH", "all AO1 L", "both B OW1 TH",
    "either IY1 DH ER0", "neither N IY1 DH ER0", "no N OW1", "none N AH1 N", "many M EH1 N IY0", "much M AH1 CH",
    "more M AO1 R", "most M OW1 S T", "few F Y UW1", "fewer F Y UW1 ER0", "less L EH1 S", "least L IY1 S T",
    "several S EH1 V R AH0 L", "enough IH0 N AH1 F", "such ~S AH0 CH", "own OW1 N", "other AH1 DH ER0",
    "another AH0 N AH1 DH ER0", "same S EY1 M", "whole HH OW1 L", "half HH AE1 F", "lot L AA1 T", "lots L AA1 T S",
    "plenty P L EH1 N T IY0", "anything EH1 N IY0 TH IH2 NG", "anyone EH1 N IY0 W AH2 N", "anybody EH1 N IY0 B AA2 D IY0",
    "anywhere EH1 N IY0 W EH2 R", "anyway EH1 N IY0 W EY2", "anyways EH1 N IY0 W EY2 Z", "anymore EH2 N IY0 M AO1 R",
    "anyhow EH1 N IY0 HH AW2",
    "everything EH1 V R IY0 TH IH2 NG", "everyone EH1 V R IY0 W AH2 N", "everybody EH1 V R IY0 B AA2 D IY0",
    "everywhere EH1 V R IY0 W EH2 R", "everyday EH1 V R IY0 D EY2",
    "something S AH1 M TH IH0 NG", "someone S AH1 M W AH2 N", "somebody S AH1 M B AA2 D IY0",
    "somewhere S AH1 M W EH2 R", "sometimes S AH0 M T AY1 M Z", "somehow S AH1 M HH AW2", "someday S AH1 M D EY2",
    "sometime S AH1 M T AY2 M", "nothing N AH1 TH IH0 NG", "nobody N OW1 B AA2 D IY0", "nowhere N OW1 W EH2 R",
    "no-one N OW1 W AH2 N",

    // ---- pronouns
    "i ~AY1", "me ~M IY0", "my ~M AY0", "mine M AY1 N", "myself M AY0 S EH1 L F", "you ~Y UW0", "your ~Y ER0",
    "yours Y UH1 R Z", "yourself Y ER0 S EH1 L F", "yourselves Y ER0 S EH1 L V Z", "he ~HH IY0", "him ~HH IH0 M",
    "his ~HH IH0 Z", "himself HH IH0 M S EH1 L F", "she ~SH IY0", "her ~HH ER0", "hers HH ER1 Z",
    "herself HH ER0 S EH1 L F", "it ~IH0 T", "its ~IH0 T S", "itself IH0 T S EH1 L F", "we ~W IY0", "us ~AH0 S",
    "our ~AW0 ER0", "ours AW1 ER0 Z", "ourselves AW0 ER0 S EH1 L V Z", "they ~DH EY0", "them ~DH EH0 M",
    "their ~DH EH0 R", "theirs DH EH1 R Z", "themselves DH EH0 M S EH1 L V Z", "one W AH1 N", "ones W AH1 N Z",
    "who HH UW1", "whom HH UW1 M", "whose HH UW1 Z", "what W AH1 T", "which W IH1 CH", "where W EH1 R",
    "when W EH1 N", "why W AY1", "how HH AW1", "whatever W AH0 T EH1 V ER0", "whoever HH UW0 EH1 V ER0",
    "wherever W EH0 R EH1 V ER0", "whenever W EH0 N EH1 V ER0", "however HH AW0 EH1 V ER0",
    "whichever W IH0 CH EH1 V ER0",

    // ---- prepositions, conjunctions, particles
    "and ~AH0 N D", "or ~AO0 R", "nor ~N AO0 R", "but ~B AH0 T", "if ~IH0 F", "than ~DH AH0 N", "then DH EH1 N",
    "because ~B IH0 K AO1 Z", "'cause ~K AH0 Z", "cause K AO1 Z", "cuz ~K AH0 Z", "though DH OW1",
    "although AO2 L DH OW1", "unless AH0 N L EH1 S", "until AH0 N T IH1 L", "till T IH1 L", "'til T IH1 L",
    "while W AY1 L", "whether ~W EH1 DH ER0", "of ~AH0 V", "to ~T UW0", "in ~IH0 N", "on ~AA0 N", "at ~AE0 T",
    "by ~B AY0", "for ~F ER0", "from ~F R AH0 M", "with ~W IH0 DH", "without W IH0 TH AW1 T",
    "within W IH0 DH IH1 N", "into ~IH0 N T UW0", "onto ~AA0 N T UW0", "upon ~AH0 P AA1 N", "about ~AH0 B AW1 T",
    "above AH0 B AH1 V", "across AH0 K R AO1 S", "after AE1 F T ER0", "afterwards AE1 F T ER0 W ER0 D Z",
    "against AH0 G EH1 N S T", "along AH0 L AO1 NG", "among AH0 M AH1 NG", "around ER0 AW1 N D", "as ~AE0 Z",
    "before B IH0 F AO1 R", "behind B IH0 HH AY1 N D", "below B IH0 L OW1", "beneath B IH0 N IY1 TH",
    "beside B IH0 S AY1 D", "besides B IH0 S AY1 D Z", "between B IH0 T W IY1 N", "beyond B IH0 Y AA1 N D",
    "down D AW1 N", "during D UH1 R IH0 NG", "except IH0 K S EH1 P T", "inside IH0 N S AY1 D", "near N IH1 R",
    "nearby N IH1 R B AY1", "off AO1 F", "out AW1 T", "outside AW1 T S AY1 D", "over OW1 V ER0", "past P AE1 S T",
    "since S IH1 N S", "through TH R UW1", "throughout TH R UW0 AW1 T", "toward T AH0 W AO1 R D",
    "towards T AH0 W AO1 R D Z", "under AH1 N D ER0", "underneath AH2 N D ER0 N IY1 TH", "up AH1 P", "upstairs AH0 P S T EH1 R Z",
    "downstairs D AW1 N S T EH1 R Z", "via V AY1 AH0", "per ~P ER0", "like L AY1 K", "unlike AH0 N L AY1 K",
    "versus V ER1 S AH0 S", "vs V ER1 S AH0 S", "via V AY1 AH0", "yet Y EH1 T", "so S OW1", "also AO1 L S OW0",
    "too T UW1", "either IY1 DH ER0", "not N AA1 T", "never N EH1 V ER0", "ever EH1 V ER0", "just JH AH1 S T",
    "only OW1 N L IY0", "even IY1 V IH0 N", "still S T IH1 L", "already AO0 L R EH1 D IY0", "again AH0 G EH1 N",
    "always AO1 L W EY2 Z", "often AO1 F AH0 N", "sometimes S AH0 M T AY1 M Z", "usually Y UW1 ZH AH0 W AH0 L IY0",
    "maybe M EY1 B IY0", "perhaps P ER0 HH AE1 P S", "probably P R AA1 B AH0 B L IY0", "almost AO1 L M OW2 S T",
    "quite K W AY1 T", "rather R AE1 DH ER0", "very V EH1 R IY0", "really R IH1 L IY0", "pretty P R IH1 T IY0",
    "together T AH0 G EH1 DH ER0", "away AH0 W EY1", "back B AE1 K", "home HH OW1 M", "else EH1 L S",
    "instead IH0 N S T EH1 D", "actually AE1 K CH UW0 AH0 L IY0", "definitely D EH1 F AH0 N AH0 T L IY0",
    "exactly IH0 G Z AE1 K T L IY0", "seriously S IH1 R IY0 AH0 S L IY0", "totally T OW1 T AH0 L IY0",
    "completely K AH0 M P L IY1 T L IY0", "absolutely AE2 B S AH0 L UW1 T L IY0", "finally F AY1 N AH0 L IY0",
    "suddenly S AH1 D AH0 N L IY0", "quickly K W IH1 K L IY0", "slowly S L OW1 L IY0", "carefully K EH1 R F AH0 L IY0",
    "here HH IH1 R", "there DH EH1 R", "now N AW1", "soon S UW1 N", "later L EY1 T ER0", "today T AH0 D EY1",
    "tonight T AH0 N AY1 T", "tomorrow T AH0 M AA1 R OW2", "yesterday Y EH1 S T ER0 D EY2", "once W AH1 N S",
    "twice T W AY1 S", "ago AH0 G OW1", "early ER1 L IY0", "late L EY1 T", "well W EH1 L", "okay OW2 K EY1",
    "ok OW2 K EY1", "yes Y EH1 S", "yeah Y AE1", "yep Y EH1 P", "yup Y AH1 P", "nope N OW1 P", "nah N AA1",
    "please P L IY1 Z", "thanks TH AE1 NG K S", "thank TH AE1 NG K", "sorry S AA1 R IY0", "hello HH AH0 L OW1",
    "hi HH AY1", "hey HH EY1", "bye B AY1", "goodbye G UH2 D B AY1", "welcome W EH1 L K AH0 M",
    "alright AO2 L R AY1 T", "sure SH UH1 R", "anyway EH1 N IY0 W EY2", "otherwise AH1 DH ER0 W AY2 Z",
    "indeed IH0 N D IY1 D", "besides B IH0 S AY1 D Z", "meanwhile M IY1 N W AY2 L", "therefore DH EH1 R F AO2 R",
    "forever F ER0 EH1 V ER0", "straight S T R EY1 T", "right R AY1 T", "left L EH1 F T", "ahead AH0 HH EH1 D",
    "aside AH0 S AY1 D", "apart AH0 P AA1 R T", "alone AH0 L OW1 N", "abroad AH0 B R AO1 D", "downtown D AW1 N T AW1 N",
    "uptown AH1 P T AW1 N", "overseas OW1 V ER0 S IY1 Z", "somewhat S AH1 M W AH2 T", "nearly N IH1 R L IY0",
    "hardly HH AA1 R D L IY0", "barely B EH1 R L IY0", "merely M IH1 R L IY0", "simply S IH1 M P L IY0",
    "especially AH0 S P EH1 SH AH0 L IY0", "certainly S ER1 T AH0 N L IY0", "obviously AA1 B V IY0 AH0 S L IY0",
    "apparently AH0 P EH1 R AH0 N T L IY0", "basically B EY1 S IH0 K L IY0", "literally L IH1 T ER0 AH0 L IY0",
    "honestly AA1 N AH0 S T L IY0", "hopefully HH OW1 P F AH0 L IY0", "unfortunately AH0 N F AO1 R CH AH0 N AH0 T L IY0",
    "immediately IH0 M IY1 D IY0 AH0 T L IY0", "recently R IY1 S AH0 N T L IY0", "eventually IH0 V EH1 N CH UW0 AH0 L IY0",
    "currently K ER1 AH0 N T L IY0", "directly D ER0 EH1 K T L IY0", "properly P R AA1 P ER0 L IY0",
    "normally N AO1 R M AH0 L IY0", "personally P ER1 S AH0 N AH0 L IY0", "possibly P AA1 S AH0 B L IY0",
    "clearly K L IH1 R L IY0", "easily IY1 Z AH0 L IY0", "badly B AE1 D L IY0", "fully F UH1 L IY0",
    "truly T R UW1 L IY0", "only OW1 N L IY0", "daily D EY1 L IY0", "nightly N AY1 T L IY0", "weekly W IY1 K L IY0",

    // ---- auxiliaries and modals (unaccented)
    "is ~IH0 Z", "am ~AE0 M", "are ~AA0 R", "was ~W AA0 Z", "were ~W ER0", "be ~B IY0", "been ~B IH0 N",
    "being B IY1 IH0 NG", "have HH AE1 V", "has ~HH AE0 Z", "had ~HH AE0 D", "having HH AE1 V IH0 NG",
    "do ~D UW0", "does ~D AH0 Z", "did ~D IH0 D", "doing D UW1 IH0 NG", "done D AH1 N", "can ~K AE0 N",
    "could ~K UH0 D", "will ~W IH0 L", "would ~W UH0 D", "shall ~SH AE0 L", "should ~SH UH0 D", "may ~M EY0",
    "might ~M AY0 T", "must ~M AH0 S T", "ought AO1 T",
    // negative contractions (accented)
    "don't D OW1 N T", "doesn't D AH1 Z AH0 N T", "didn't D IH1 D AH0 N T", "can't K AE1 N T",
    "cannot K AE1 N AA0 T", "won't W OW1 N T", "wouldn't W UH1 D AH0 N T", "couldn't K UH1 D AH0 N T",
    "shouldn't SH UH1 D AH0 N T", "isn't IH1 Z AH0 N T", "aren't AA1 R AH0 N T", "wasn't W AA1 Z AH0 N T",
    "weren't W ER1 N T", "haven't HH AE1 V AH0 N T", "hasn't HH AE1 Z AH0 N T", "hadn't HH AE1 D AH0 N T",
    "ain't EY1 N T", "mustn't M AH1 S AH0 N T", "needn't N IY1 D AH0 N T", "mightn't M AY1 T AH0 N T",
    "shan't SH AE1 N T",
    // pronoun contractions
    "i'm ~AY1 M", "i've ~AY1 V", "i'll ~AY1 L", "i'd ~AY1 D", "you're ~Y UH0 R", "you've ~Y UW0 V",
    "you'll ~Y UW0 L", "you'd ~Y UW0 D", "he's ~HH IY0 Z", "he'll ~HH IY0 L", "he'd ~HH IY0 D", "she's ~SH IY0 Z",
    "she'll ~SH IY0 L", "she'd ~SH IY0 D", "it's ~IH0 T S", "it'll ~IH0 T AH0 L", "it'd ~IH0 T AH0 D",
    "we're ~W IH0 R", "we've ~W IY0 V", "we'll ~W IY0 L", "we'd ~W IY0 D", "they're ~DH EH0 R",
    "they've ~DH EY0 V", "they'll ~DH EY0 L", "they'd ~DH EY0 D", "that's ~DH AE0 T S", "that'll DH AE1 T AH0 L",
    "that'd DH AE1 T AH0 D", "there's ~DH EH0 R Z", "there'll DH EH1 R AH0 L", "here's HH IH1 R Z",
    "what's W AH1 T S", "what'll W AH1 T AH0 L", "what'd W AH1 T AH0 D", "who's HH UW1 Z", "who'll HH UW1 L",
    "who'd HH UW1 D", "where's W EH1 R Z", "where'd W EH1 R D", "when's W EH1 N Z", "why's W AY1 Z",
    "how's HH AW1 Z", "how'd HH AW1 D", "let's L EH1 T S", "y'all Y AO1 L", "ma'am M AE1 M",
    "o'clock AH0 K L AA1 K", "'em ~AH0 M", "c'mon K AH0 M AA1 N", "ol' OW1 L", "'bout ~AH0 B AW1 T",
    "gonna G AA1 N AH0", "wanna W AA1 N AH0", "gotta G AA1 T AH0", "gimme G IH1 M IY0", "lemme L EH1 M IY0",
    "dunno D AH0 N OW1", "kinda K AY1 N D AH0", "sorta S AO1 R T AH0", "outta AW1 T AH0", "lotta L AA1 T AH0",
    "ya ~Y AH0", "yall Y AO1 L", "whatcha W AH1 CH AH0", "gotcha G AA1 CH AH0", "betcha B EH1 CH AH0",
    "dontcha D OW1 N CH AH0", "wassup W AH0 S AH1 P", "sup S AH1 P", "innit IH1 N IH0 T", "nothin N AH1 TH IH0 N",

    // ---- numbers
    "zero Z IH1 R OW0", "oh OW1", "two T UW1", "three TH R IY1", "four F AO1 R", "five F AY1 V", "six S IH1 K S",
    "seven S EH1 V AH0 N", "eight EY1 T", "nine N AY1 N", "ten T EH1 N", "eleven IH0 L EH1 V AH0 N",
    "twelve T W EH1 L V", "thirteen TH ER1 T IY1 N", "fourteen F AO1 R T IY1 N", "fifteen F IH0 F T IY1 N",
    "sixteen S IH0 K S T IY1 N", "seventeen S EH1 V AH0 N T IY1 N", "eighteen EY0 T IY1 N",
    "nineteen N AY1 N T IY1 N", "twenty T W EH1 N T IY0", "thirty TH ER1 T IY0", "forty F AO1 R T IY0",
    "fifty F IH1 F T IY0", "sixty S IH1 K S T IY0", "seventy S EH1 V AH0 N T IY0", "eighty EY1 T IY0",
    "ninety N AY1 N T IY0", "hundred HH AH1 N D R AH0 D", "thousand TH AW1 Z AH0 N D", "million M IH1 L Y AH0 N",
    "billion B IH1 L Y AH0 N", "trillion T R IH1 L Y AH0 N", "first F ER1 S T", "second S EH1 K AH0 N D",
    "third TH ER1 D", "fourth F AO1 R TH", "fifth F IH1 F TH", "sixth S IH1 K S TH", "seventh S EH1 V AH0 N TH",
    "eighth EY1 T TH", "ninth N AY1 N TH", "tenth T EH1 N TH", "eleventh IH0 L EH1 V AH0 N TH",
    "twelfth T W EH1 L F TH", "thirteenth TH ER1 T IY1 N TH", "fourteenth F AO1 R T IY1 N TH",
    "fifteenth F IH0 F T IY1 N TH", "sixteenth S IH0 K S T IY1 N TH", "seventeenth S EH1 V AH0 N T IY1 N TH",
    "eighteenth EY0 T IY1 N TH", "nineteenth N AY1 N T IY1 N TH", "twentieth T W EH1 N T IY0 AH0 TH",
    "thirtieth TH ER1 T IY0 AH0 TH", "fortieth F AO1 R T IY0 AH0 TH", "fiftieth F IH1 F T IY0 AH0 TH",
    "sixtieth S IH1 K S T IY0 AH0 TH", "seventieth S EH1 V AH0 N T IY0 AH0 TH", "eightieth EY1 T IY0 AH0 TH",
    "ninetieth N AY1 N T IY0 AH0 TH", "hundredth HH AH1 N D R AH0 D TH", "thousandth TH AW1 Z AH0 N D TH",
    "millionth M IH1 L Y AH0 N TH", "billionth B IH1 L Y AH0 N TH", "point P OY1 N T", "percent P ER0 S EH1 N T",
    "dollar D AA1 L ER0", "dollars D AA1 L ER0 Z", "cent S EH1 N T", "cents S EH1 N T S", "minus M AY1 N AH0 S",
    "plus P L AH1 S", "times T AY1 M Z", "quarter K W AO1 R T ER0", "dozen D AH1 Z AH0 N", "double D AH1 B AH0 L",
    "triple T R IH1 P AH0 L", "single S IH1 NG G AH0 L", "number N AH1 M B ER0", "numbers N AH1 M B ER0 Z",
    "grand G R AE1 N D", "buck B AH1 K", "bucks B AH1 K S", "k K EY1", "mil M IH1 L",

    // ---- time
    "time T AY1 M", "day D EY1", "days D EY1 Z", "night N AY1 T", "morning M AO1 R N IH0 NG",
    "afternoon AE2 F T ER0 N UW1 N", "evening IY1 V N IH0 NG", "noon N UW1 N", "midnight M IH1 D N AY2 T",
    "week W IY1 K", "weekend W IY1 K EH2 N D", "month M AH1 N TH", "months M AH1 N TH S", "year Y IH1 R",
    "hour AW1 ER0", "hours AW1 ER0 Z", "minute M IH1 N AH0 T", "minutes M IH1 N AH0 T S", "moment M OW1 M AH0 N T",
    "clock K L AA1 K", "date D EY1 T", "season S IY1 Z AH0 N", "summer S AH1 M ER0", "winter W IH1 N T ER0",
    "spring S P R IH1 NG", "fall F AO1 L", "autumn AO1 T AH0 M", "century S EH1 N CH ER0 IY0", "past P AE1 S T",
    "future F Y UW1 CH ER0", "present P R EH1 Z AH0 N T", "monday M AH1 N D EY2", "tuesday T UW1 Z D EY2",
    "wednesday W EH1 N Z D EY2", "thursday TH ER1 Z D EY2", "friday F R AY1 D EY2", "saturday S AE1 T ER0 D EY2",
    "sunday S AH1 N D EY2", "january JH AE1 N Y UW0 EH2 R IY0", "february F EH1 B Y UW0 EH2 R IY0",
    "march M AA1 R CH", "april EY1 P R AH0 L", "june JH UW1 N", "july JH UW0 L AY1", "august AA1 G AH0 S T",
    "september S EH0 P T EH1 M B ER0", "october AA0 K T OW1 B ER0", "november N OW0 V EH1 M B ER0",
    "december D IH0 S EH1 M B ER0", "am EY1 EH1 M", "pm P IY1 EH1 M",

    // ---- common verbs (base forms) and irregular forms
    "accept AE0 K S EH1 P T", "act AE1 K T", "add AE1 D", "admit AH0 D M IH1 T", "afford AH0 F AO1 R D",
    "agree AH0 G R IY1", "aim EY1 M", "allow AH0 L AW1", "answer AE1 N S ER0", "appear AH0 P IH1 R",
    "apply AH0 P L AY1", "approach AH0 P R OW1 CH", "argue AA1 R G Y UW0", "arrest ER0 EH1 S T",
    "arrive ER0 AY1 V", "ask AE1 S K", "attack AH0 T AE1 K", "avoid AH0 V OY1 D", "bake B EY1 K", "bark B AA1 R K",
    "bear B EH1 R", "beat B IY1 T", "beaten B IY1 T AH0 N", "become B IH0 K AH1 M", "became B IH0 K EY1 M",
    "beg B EH1 G", "begin B IH0 G IH1 N", "began B IH0 G AE1 N", "begun B IH0 G AH1 N", "believe B IH0 L IY1 V",
    "belong B IH0 L AO1 NG", "bend B EH1 N D", "bent B EH1 N T", "bet B EH1 T", "bite B AY1 T", "bit B IH1 T",
    "bitten B IH1 T AH0 N", "blame B L EY1 M", "bleed B L IY1 D", "bled B L EH1 D", "bless B L EH1 S",
    "blow B L OW1", "blew B L UW1", "blown B L OW1 N", "boil B OY1 L", "borrow B AA1 R OW0", "bother B AA1 DH ER0",
    "break B R EY1 K", "broke B R OW1 K", "broken B R OW1 K AH0 N", "breathe B R IY1 DH", "bring B R IH1 NG",
    "brought B R AO1 T", "build B IH1 L D", "built B IH1 L T", "burn B ER1 N", "burst B ER1 S T",
    "bury B EH1 R IY0", "buy B AY1", "bought B AO1 T", "call K AO1 L", "calm K AA1 M", "care K EH1 R",
    "carry K AE1 R IY0", "catch K AE1 CH", "caught K AO1 T", "change CH EY1 N JH", "charge CH AA1 R JH",
    "chase CH EY1 S", "cheat CH IY1 T", "check CH EH1 K", "choose CH UW1 Z", "chose CH OW1 Z",
    "chosen CH OW1 Z AH0 N", "clean K L IY1 N", "clear K L IH1 R", "climb K L AY1 M", "close K L OW1 Z",
    "collect K AH0 L EH1 K T", "come K AH1 M", "came K EY1 M", "coming K AH1 M IH0 NG", "complain K AH0 M P L EY1 N",
    "confirm K AH0 N F ER1 M", "consider K AH0 N S IH1 D ER0", "continue K AH0 N T IH1 N Y UW0",
    "control K AH0 N T R OW1 L", "cook K UH1 K", "cost K AO1 S T", "count K AW1 N T", "cover K AH1 V ER0",
    "crash K R AE1 SH", "cross K R AO1 S", "cry K R AY1", "cut K AH1 T", "dance D AE1 N S", "dare D EH1 R",
    "deal D IY1 L", "dealt D EH1 L T", "decide D IH0 S AY1 D", "deliver D IH0 L IH1 V ER0", "deny D IH0 N AY1",
    "deserve D IH0 Z ER1 V", "destroy D IH0 S T R OY1", "die D AY1", "died D AY1 D", "dies D AY1 Z",
    "dying D AY1 IH0 NG", "dig D IH1 G", "dug D AH1 G", "disappear D IH2 S AH0 P IH1 R", "drag D R AE1 G",
    "draw D R AO1", "drew D R UW1", "drawn D R AO1 N", "dream D R IY1 M", "dress D R EH1 S", "drink D R IH1 NG K",
    "drank D R AE1 NG K", "drunk D R AH1 NG K", "drive D R AY1 V", "drove D R OW1 V", "driven D R IH1 V AH0 N",
    "drop D R AA1 P", "earn ER1 N", "eat IY1 T", "ate EY1 T", "eaten IY1 T AH0 N", "end EH1 N D",
    "enjoy EH0 N JH OY1", "enter EH1 N T ER0", "escape IH0 S K EY1 P", "expect IH0 K S P EH1 K T",
    "explain IH0 K S P L EY1 N", "explode IH0 K S P L OW1 D", "fail F EY1 L", "fall F AO1 L", "fell F EH1 L",
    "fallen F AO1 L AH0 N", "feed F IY1 D", "fed F EH1 D", "feel F IY1 L", "felt F EH1 L T", "fight F AY1 T",
    "fought F AO1 T", "figure F IH1 G Y ER0", "fill F IH1 L", "find F AY1 N D", "found F AW1 N D",
    "finish F IH1 N IH0 SH", "fire F AY1 ER0", "fix F IH1 K S", "flee F L IY1", "fled F L EH1 D", "fly F L AY1",
    "flew F L UW1", "flown F L OW1 N", "follow F AA1 L OW0", "forget F ER0 G EH1 T", "forgot F ER0 G AA1 T",
    "forgotten F ER0 G AA1 T AH0 N", "forgive F ER0 G IH1 V", "freeze F R IY1 Z", "froze F R OW1 Z",
    "frozen F R OW1 Z AH0 N", "get G EH1 T", "got G AA1 T", "gotten G AA1 T AH0 N", "give G IH1 V",
    "gave G EY1 V", "given G IH1 V AH0 N", "go G OW1", "goes G OW1 Z", "going G OW1 IH0 NG", "went W EH1 N T",
    "gone G AO1 N", "grab G R AE1 B", "grow G R OW1", "grew G R UW1", "grown G R OW1 N", "guess G EH1 S",
    "hang HH AE1 NG", "hung HH AH1 NG", "happen HH AE1 P AH0 N", "hate HH EY1 T", "hear HH IH1 R",
    "heard HH ER1 D", "help HH EH1 L P", "hide HH AY1 D", "hid HH IH1 D", "hidden HH IH1 D AH0 N", "hit HH IH1 T",
    "hold HH OW1 L D", "held HH EH1 L D", "hope HH OW1 P", "hunt HH AH1 N T", "hurry HH ER1 IY0", "hurt HH ER1 T",
    "imagine IH0 M AE1 JH AH0 N", "include IH0 N K L UW1 D", "join JH OY1 N", "jump JH AH1 M P", "keep K IY1 P",
    "kept K EH1 P T", "kick K IH1 K", "kill K IH1 L", "kiss K IH1 S", "knock N AA1 K", "know N OW1", "knew N UW1",
    "known N OW1 N", "land L AE1 N D", "last L AE1 S T", "laugh L AE1 F", "lay L EY1", "laid L EY1 D",
    "lead L IY1 D", "led L EH1 D", "learn L ER1 N", "leave L IY1 V", "lend L EH1 N D", "lent L EH1 N T",
    "let L EH1 T", "lie L AY1", "lied L AY1 D", "lying L AY1 IH0 NG", "lift L IH1 F T", "light L AY1 T",
    "lit L IH1 T", "listen L IH1 S AH0 N", "live L IH1 V", "load L OW1 D", "lock L AA1 K", "look L UH1 K",
    "lose L UW1 Z", "lost L AO1 S T", "love L AH1 V", "make M EY1 K", "made M EY1 D", "manage M AE1 N AH0 JH",
    "marry M EH1 R IY0", "matter M AE1 T ER0", "mean M IY1 N", "meant M EH1 N T", "meet M IY1 T", "met M EH1 T",
    "mind M AY1 N D", "miss M IH1 S", "move M UW1 V", "need N IY1 D", "notice N OW1 T AH0 S", "offer AO1 F ER0",
    "open OW1 P AH0 N", "order AO1 R D ER0", "pack P AE1 K", "park P AA1 R K", "pass P AE1 S", "pay P EY1",
    "paid P EY1 D", "pick P IH1 K", "plan P L AE1 N", "play P L EY1", "pray P R EY1", "prepare P R IY0 P EH1 R",
    "press P R EH1 S", "pretend P R IY0 T EH1 N D", "promise P R AA1 M AH0 S", "protect P R AH0 T EH1 K T",
    "prove P R UW1 V", "pull P UH1 L", "punch P AH1 N CH", "push P UH1 SH", "put P UH1 T", "quit K W IH1 T",
    "rain R EY1 N", "raise R EY1 Z", "reach R IY1 CH", "read R IY1 D", "realize R IY1 AH0 L AY2 Z",
    "receive R IH0 S IY1 V", "recognize R EH1 K AH0 G N AY2 Z", "relax R IH0 L AE1 K S",
    "remember R IH0 M EH1 M B ER0", "remind R IY0 M AY1 N D", "rent R EH1 N T", "repeat R IH0 P IY1 T",
    "report R IH0 P AO1 R T", "rescue R EH1 S K Y UW0", "rest R EH1 S T", "return R IH0 T ER1 N", "ride R AY1 D",
    "rode R OW1 D", "ridden R IH1 D AH0 N", "ring R IH1 NG", "rang R AE1 NG", "rung R AH1 NG", "rise R AY1 Z",
    "rose R OW1 Z", "risk R IH1 S K", "rob R AA1 B", "roll R OW1 L", "run R AH1 N", "ran R AE1 N", "rush R AH1 SH",
    "save S EY1 V", "say S EY1", "said S EH1 D", "says S EH1 Z", "scream S K R IY1 M", "search S ER1 CH",
    "see S IY1", "saw S AO1", "seen S IY1 N", "seem S IY1 M", "sell S EH1 L", "sold S OW1 L D", "send S EH1 N D",
    "sent S EH1 N T", "serve S ER1 V", "set S EH1 T", "settle S EH1 T AH0 L", "shake SH EY1 K", "shook SH UH1 K",
    "share SH EH1 R", "shoot SH UW1 T", "shot SH AA1 T", "shop SH AA1 P", "shout SH AW1 T", "show SH OW1",
    "shown SH OW1 N", "shut SH AH1 T", "sing S IH1 NG", "sang S AE1 NG", "sung S AH1 NG", "sink S IH1 NG K",
    "sank S AE1 NG K", "sit S IH1 T", "sat S AE1 T", "sleep S L IY1 P", "slept S L EH1 P T", "slide S L AY1 D",
    "slid S L IH1 D", "smell S M EH1 L", "smile S M AY1 L", "smoke S M OW1 K", "speak S P IY1 K",
    "spoke S P OW1 K", "spoken S P OW1 K AH0 N", "spend S P EH1 N D", "spent S P EH1 N T", "stand S T AE1 N D",
    "stood S T UH1 D", "start S T AA1 R T", "stay S T EY1", "steal S T IY1 L", "stole S T OW1 L",
    "stolen S T OW1 L AH0 N", "step S T EH1 P", "stick S T IH1 K", "stuck S T AH1 K", "stop S T AA1 P",
    "strike S T R AY1 K", "struck S T R AH1 K", "study S T AH1 D IY0", "succeed S AH0 K S IY1 D",
    "suggest S AH0 G JH EH1 S T", "suppose S AH0 P OW1 Z", "surprise S ER0 P R AY1 Z",
    "surrender S ER0 EH1 N D ER0", "survive S ER0 V AY1 V", "swear S W EH1 R", "swore S W AO1 R",
    "swim S W IH1 M", "swam S W AE1 M", "swing S W IH1 NG", "swung S W AH1 NG", "take T EY1 K", "took T UH1 K",
    "taken T EY1 K AH0 N", "talk T AO1 K", "taste T EY1 S T", "teach T IY1 CH", "taught T AO1 T", "tell T EH1 L",
    "told T OW1 L D", "think TH IH1 NG K", "thought TH AO1 T", "threaten TH R EH1 T AH0 N", "throw TH R OW1",
    "threw TH R UW1", "thrown TH R OW1 N", "touch T AH1 CH", "trade T R EY1 D", "travel T R AE1 V AH0 L",
    "trust T R AH1 S T", "try T R AY1", "tried T R AY1 D", "tries T R AY1 Z", "turn T ER1 N",
    "understand AH2 N D ER0 S T AE1 N D", "understood AH2 N D ER0 S T UH1 D", "use Y UW1 Z", "visit V IH1 Z IH0 T",
    "wait W EY1 T", "wake W EY1 K", "woke W OW1 K", "walk W AO1 K", "want W AA1 N T", "warn W AO1 R N",
    "wash W AA1 SH", "waste W EY1 S T", "watch W AA1 CH", "wear W EH1 R", "wore W AO1 R", "worn W AO1 R N",
    "win W IH1 N", "won W AH1 N", "wish W IH1 SH", "wonder W AH1 N D ER0", "work W ER1 K", "worry W ER1 IY0",
    "write R AY1 T", "wrote R OW1 T", "written R IH1 T AH0 N", "yell Y EH1 L", "seek S IY1 K", "sought S AO1 T",
    "shine SH AY1 N", "shone SH OW1 N", "tear T EH1 R", "tore T AO1 R", "torn T AO1 R N", "bind B AY1 N D",
    "bound B AW1 N D", "wind W IH1 N D", "wound W UW1 N D", "lean L IY1 N", "leap L IY1 P", "spit S P IH1 T",
    "spat S P AE1 T", "spin S P IH1 N", "spun S P AH1 N", "split S P L IH1 T", "spread S P R EH1 D",
    "sweep S W IY1 P", "swept S W EH1 P T", "weep W IY1 P", "wept W EH1 P T", "creep K R IY1 P",
    "crept K R EH1 P T", "kneel N IY1 L", "knelt N EH1 L T", "sting S T IH1 NG", "stung S T AH1 NG",
    "hurl HH ER1 L", "own OW1 N", "owe OW1", "admire AE0 D M AY1 R", "adopt AH0 D AA1 P T",
    "advise AE0 D V AY1 Z", "announce AH0 N AW1 N S", "arrange ER0 EY1 N JH", "assume AH0 S UW1 M",
    "attend AH0 T EH1 N D", "beware B IH0 W EH1 R", "blast B L AE1 S T", "block B L AA1 K", "board B AO1 R D",
    "bounce B AW1 N S", "burglarize B ER1 G L ER0 AY2 Z", "calculate K AE1 L K Y AH0 L EY2 T", "celebrate S EH1 L AH0 B R EY2 T",
    "chill CH IH1 L", "claim K L EY1 M", "commit K AH0 M IH1 T", "compare K AH0 M P EH1 R",
    "complete K AH0 M P L IY1 T", "connect K AH0 N EH1 K T", "contact K AA1 N T AE2 K T", "convince K AH0 N V IH1 N S",
    "create K R IY0 EY1 T", "damage D AE1 M AH0 JH", "defend D IH0 F EH1 N D", "delay D IH0 L EY1",
    "depend D IH0 P EH1 N D", "describe D IH0 S K R AY1 B", "develop D IH0 V EH1 L AH0 P", "disagree D IH2 S AH0 G R IY1",
    "discover D IH0 S K AH1 V ER0", "discuss D IH0 S K AH1 S", "divide D IH0 V AY1 D", "doubt D AW1 T",
    "download D AW1 N L OW2 D", "earn ER1 N", "encourage EH0 N K ER1 IH0 JH", "establish IH0 S T AE1 B L IH0 SH",
    "exist IH0 G Z IH1 S T", "express IH0 K S P R EH1 S", "face F EY1 S", "fear F IH1 R", "fetch F EH1 CH",
    "force F AO1 R S", "gather G AE1 DH ER0", "greet G R IY1 T", "guard G AA1 R D", "handle HH AE1 N D AH0 L",
    "hijack HH AY1 JH AE2 K", "hire HH AY1 ER0", "honk HH AA1 NG K", "identify AY0 D EH1 N T AH0 F AY2",
    "ignore IH0 G N AO1 R", "improve IH0 M P R UW1 V", "increase IH0 N K R IY1 S", "inform IH0 N F AO1 R M",
    "insist IH0 N S IH1 S T", "install IH0 N S T AO1 L", "intend IH0 N T EH1 N D", "introduce IH2 N T R AH0 D UW1 S",
    "invest IH0 N V EH1 S T", "investigate IH0 N V EH1 S T AH0 G EY2 T", "invite IH0 N V AY1 T", "joke JH OW1 K",
    "judge JH AH1 JH", "kidnap K IH1 D N AE2 P", "launch L AO1 N CH", "limit L IH1 M AH0 T", "link L IH1 NG K",
    "mention M EH1 N SH AH0 N", "murder M ER1 D ER0", "obey OW0 B EY1", "operate AA1 P ER0 EY2 T",
    "organize AO1 R G AH0 N AY2 Z", "panic P AE1 N IH0 K", "perform P ER0 F AO1 R M", "permit P ER0 M IH1 T",
    "pour P AO1 R", "prefer P R IH0 F ER1", "produce P R AH0 D UW1 S", "provide P R AH0 V AY1 D",
    "pursue P ER0 S UW1", "quote K W OW1 T", "react R IY0 AE1 K T", "record R IH0 K AO1 R D", "reduce R IH0 D UW1 S",
    "refuse R IH0 F Y UW1 Z", "release R IY0 L IY1 S", "rely R IH0 L AY1", "remain R IH0 M EY1 N",
    "remove R IY0 M UW1 V", "replace R IY0 P L EY1 S", "reply R IH0 P L AY1", "request R IH0 K W EH1 S T",
    "require R IY0 K W AY1 ER0", "respect R IH0 S P EH1 K T", "respond R IH0 S P AA1 N D", "reveal R IH0 V IY1 L",
    "ruin R UW1 IH0 N", "sail S EY1 L", "scare S K EH1 R", "select S AH0 L EH1 K T", "shove SH AH1 V",
    "sign S AY1 N", "smash S M AE1 SH", "sneak S N IY1 K", "solve S AA1 L V", "spray S P R EY1", "squeeze S K W IY1 Z",
    "stab S T AE1 B", "stare S T EH1 R", "steer S T IH1 R", "store S T AO1 R", "struggle S T R AH1 G AH0 L",
    "suffer S AH1 F ER0", "support S AH0 P AO1 R T", "surround S ER0 AW1 N D", "suspect S AH0 S P EH1 K T",
    "swallow S W AA1 L OW0", "switch S W IH1 CH", "tap T AE1 P", "target T AA1 R G AH0 T", "test T EH1 S T",
    "text T EH1 K S T", "thrive TH R AY1 V", "tie T AY1", "track T R AE1 K", "train T R EY1 N", "trap T R AE1 P",
    "treat T R IY1 T", "trick T R IH1 K", "type T AY1 P", "vote V OW1 T", "wander W AA1 N D ER0",
    "whisper W IH1 S P ER0", "wipe W AY1 P", "worship W ER1 SH AH0 P", "wrap R AE1 P", "wreck R EH1 K",

    // ---- people, family, body
    "man M AE1 N", "men M EH1 N", "woman W UH1 M AH0 N", "women W IH1 M AH0 N", "person P ER1 S AH0 N",
    "people P IY1 P AH0 L", "child CH AY1 L D", "children CH IH1 L D R AH0 N", "kid K IH1 D", "baby B EY1 B IY0",
    "boy B OY1", "girl G ER1 L", "guy G AY1", "lady L EY1 D IY0", "ladies L EY1 D IY0 Z", "gentleman JH EH1 N T AH0 L M AH0 N",
    "gentlemen JH EH1 N T AH0 L M EH0 N", "sir S ER1", "madam M AE1 D AH0 M", "mister M IH1 S T ER0",
    "mr M IH1 S T ER0", "mrs M IH1 S IH0 Z", "missus M IH1 S IH0 Z", "miss M IH1 S", "ms M IH1 Z",
    "family F AE1 M AH0 L IY0", "mother M AH1 DH ER0", "father F AA1 DH ER0", "mom M AA1 M", "mama M AA1 M AH0",
    "dad D AE1 D", "daddy D AE1 D IY0", "papa P AA1 P AH0", "brother B R AH1 DH ER0", "sister S IH1 S T ER0",
    "son S AH1 N", "daughter D AO1 T ER0", "wife W AY1 F", "wives W AY1 V Z", "husband HH AH1 Z B AH0 N D",
    "uncle AH1 NG K AH0 L", "aunt AE1 N T", "cousin K AH1 Z AH0 N", "nephew N EH1 F Y UW0", "niece N IY1 S",
    "grandma G R AE1 N M AA2", "grandpa G R AE1 N P AA2", "grandmother G R AE1 N D M AH2 DH ER0",
    "grandfather G R AE1 N D F AA2 DH ER0", "parent P EH1 R AH0 N T", "friend F R EH1 N D", "enemy EH1 N AH0 M IY0",
    "partner P AA1 R T N ER0", "neighbor N EY1 B ER0", "stranger S T R EY1 N JH ER0", "client K L AY1 AH0 N T",
    "customer K AH1 S T AH0 M ER0", "boss B AO1 S", "chief CH IY1 F", "king K IH1 NG", "queen K W IY1 N",
    "prince P R IH1 N S", "princess P R IH1 N S EH0 S", "god G AA1 D", "jesus JH IY1 Z AH0 S", "christ K R AY1 S T",
    "lord L AO1 R D", "dude D UW1 D", "bro B R OW1", "bruh B R AH1", "homie HH OW1 M IY0", "homeboy HH OW1 M B OY2",
    "buddy B AH1 D IY0", "pal P AE1 L", "folks F OW1 K S", "folk F OW1 K", "fella F EH1 L AH0", "kiddo K IH1 D OW0",
    "honey HH AH1 N IY0", "sweetheart S W IY1 T HH AA2 R T", "darling D AA1 R L IH0 NG", "babe B EY1 B",
    "body B AA1 D IY0", "head HH EH1 D", "face F EY1 S", "eye AY1", "eyes AY1 Z", "ear IH1 R", "nose N OW1 Z",
    "mouth M AW1 TH", "lip L IH1 P", "tongue T AH1 NG", "tooth T UW1 TH", "teeth T IY1 TH", "neck N EH1 K",
    "shoulder SH OW1 L D ER0", "arm AA1 R M", "hand HH AE1 N D", "finger F IH1 NG G ER0", "thumb TH AH1 M",
    "chest CH EH1 S T", "heart HH AA1 R T", "stomach S T AH1 M AH0 K", "belly B EH1 L IY0", "back B AE1 K",
    "leg L EH1 G", "knee N IY1", "foot F UH1 T", "feet F IY1 T", "toe T OW1", "skin S K IH1 N", "hair HH EH1 R",
    "blood B L AH1 D", "bone B OW1 N", "brain B R EY1 N", "mind M AY1 N D", "soul S OW1 L", "life L AY1 F",
    "lives L AY1 V Z", "death D EH1 TH", "health HH EH1 L TH", "voice V OY1 S", "breath B R EH1 TH",

    // ---- crime, police, weapons
    "police P AH0 L IY1 S", "policeman P AH0 L IY1 S M AH0 N", "cop K AA1 P", "cops K AA1 P S",
    "officer AO1 F AH0 S ER0", "sheriff SH EH1 R AH0 F", "deputy D EH1 P Y AH0 T IY0", "detective D IH0 T EH1 K T IH0 V",
    "sergeant S AA1 R JH AH0 N T", "lieutenant L UW0 T EH1 N AH0 N T", "captain K AE1 P T AH0 N",
    "agent EY1 JH AH0 N T", "federal F EH1 D ER0 AH0 L", "feds F EH1 D Z", "cruiser K R UW1 Z ER0",
    "patrol P AH0 T R OW1 L", "dispatch D IH0 S P AE1 CH", "unit Y UW1 N AH0 T", "units Y UW1 N AH0 T S",
    "backup B AE1 K AH2 P", "suspect S AH1 S P EH2 K T", "suspects S AH1 S P EH2 K T S", "witness W IH1 T N AH0 S",
    "victim V IH1 K T AH0 M", "crime K R AY1 M", "criminal K R IH1 M AH0 N AH0 L", "murder M ER1 D ER0",
    "murderer M ER1 D ER0 ER0", "killer K IH1 L ER0", "robbery R AA1 B ER0 IY0", "robber R AA1 B ER0",
    "thief TH IY1 F", "thieves TH IY1 V Z", "heist HH AY1 S T", "theft TH EH1 F T", "gang G AE1 NG",
    "gangster G AE1 NG S T ER0", "mob M AA1 B", "mafia M AA1 F IY0 AH0", "cartel K AA0 R T EH1 L", "crew K R UW1",
    "hitman HH IH1 T M AE2 N", "hustler HH AH1 S L ER0", "dealer D IY1 L ER0", "drug D R AH1 G", "drugs D R AH1 G Z",
    "dope D OW1 P", "stash S T AE1 SH", "deal D IY1 L", "score S K AO1 R", "job JH AA1 B", "jail JH EY1 L",
    "prison P R IH1 Z AH0 N", "cell S EH1 L", "court K AO1 R T", "judge JH AH1 JH", "jury JH UH1 R IY0",
    "lawyer L AO1 Y ER0", "attorney AH0 T ER1 N IY0", "law L AO1", "justice JH AH1 S T AH0 S", "guilty G IH1 L T IY0",
    "innocent IH1 N AH0 S AH0 N T", "bail B EY1 L", "warrant W AO1 R AH0 N T", "arrest ER0 EH1 S T",
    "handcuffs HH AE1 N D K AH2 F S", "badge B AE1 JH", "wanted W AA1 N T IH0 D", "busted B AH1 S T AH0 D",
    "wasted W EY1 S T AH0 D", "gun G AH1 N", "guns G AH1 N Z", "pistol P IH1 S T AH0 L", "rifle R AY1 F AH0 L",
    "shotgun SH AA1 T G AH2 N", "weapon W EH1 P AH0 N", "weapons W EH1 P AH0 N Z", "knife N AY1 F",
    "knives N AY1 V Z", "bullet B UH1 L AH0 T", "bullets B UH1 L AH0 T S", "ammo AE1 M OW0",
    "ammunition AE2 M Y AH0 N IH1 SH AH0 N", "bomb B AA1 M", "grenade G R AH0 N EY1 D", "rocket R AA1 K AH0 T",
    "explosion IH0 K S P L OW1 ZH AH0 N", "shots SH AA1 T S", "shooting SH UW1 T IH0 NG", "fire F AY1 ER0",
    "fired F AY1 ER0 D", "trigger T R IH1 G ER0", "armed AA1 R M D", "dangerous D EY1 N JH ER0 AH0 S",
    "danger D EY1 N JH ER0", "threat TH R EH1 T", "hostage HH AA1 S T IH0 JH", "ransom R AE1 N S AH0 M",
    "chase CH EY1 S", "pursuit P ER0 S UW1 T", "escape IH0 S K EY1 P", "getaway G EH1 T AH0 W EY2",
    "roadblock R OW1 D B L AA2 K", "helicopter HH EH1 L AH0 K AA2 P T ER0", "chopper CH AA1 P ER0",
    "siren S AY1 R AH0 N", "alarm AH0 L AA1 R M", "vault V AO1 L T", "safe S EY1 F", "evidence EH1 V AH0 D AH0 N S",
    "case K EY1 S", "file F AY1 L", "code K OW1 D", "copy K AA1 P IY0", "roger R AA1 JH ER0", "over OW1 V ER0",
    "respond R IH0 S P AA1 N D", "responding R IH0 S P AA1 N D IH0 NG", "requesting R IH0 K W EH1 S T IH0 NG",
    "advised AE0 D V AY1 Z D", "possible P AA1 S AH0 B AH0 L", "male M EY1 L", "female F IY1 M EY2 L",
    "vehicle V IY1 HH IH0 K AH0 L", "vehicles V IY1 HH IH0 K AH0 L Z", "license L AY1 S AH0 N S", "plate P L EY1 T",
    "northbound N AO1 R TH B AW2 N D", "southbound S AW1 TH B AW2 N D", "eastbound IY1 S T B AW2 N D",
    "westbound W EH1 S T B AW2 N D", "intersection IH2 N T ER0 S EH1 K SH AH0 N", "heading HH EH1 D IH0 NG",
    "surveillance S ER0 V EY1 L AH0 N S", "informant IH0 N F AO1 R M AH0 N T", "snitch S N IH1 CH", "rat R AE1 T",
    "traitor T R EY1 T ER0", "loyal L OY1 AH0 L", "loyalty L OY1 AH0 L T IY0", "respect R IH0 S P EH1 K T",
    "revenge R IY0 V EH1 N JH", "territory T EH1 R AH0 T AO2 R IY0", "turf T ER1 F", "hood HH UH1 D",
    "ghetto G EH1 T OW0", "street S T R IY1 T", "streets S T R IY1 T S", "corner K AO1 R N ER0", "alley AE1 L IY0",
    "trouble T R AH1 B AH0 L", "problem P R AA1 B L AH0 M", "business B IH1 Z N AH0 S", "payback P EY1 B AE2 K",
    "debt D EH1 T", "loan L OW1 N", "cash K AE1 SH", "money M AH1 N IY0", "moneys M AH1 N IY0 Z",
    "payment P EY1 M AH0 N T", "price P R AY1 S", "cost K AO1 S T", "bank B AE1 NG K", "wallet W AA1 L AH0 T",
    "rich R IH1 CH", "poor P UH1 R", "broke B R OW1 K", "loot L UW1 T", "diamond D AY1 M AH0 N D",
    "diamonds D AY1 M AH0 N D Z", "gold G OW1 L D", "jewelry JH UW1 AH0 L R IY0", "watch W AA1 CH",
    "package P AE1 K IH0 JH", "delivery D IH0 L IH1 V ER0 IY0", "shipment SH IH1 P M AH0 N T", "cargo K AA1 R G OW0",
    "contraband K AA1 N T R AH0 B AE2 N D", "smuggler S M AH1 G L ER0", "boss B AO1 S",

    // ---- vehicles and driving
    "car K AA1 R", "cars K AA1 R Z", "truck T R AH1 K", "van V AE1 N", "bus B AH1 S", "taxi T AE1 K S IY0",
    "cab K AE1 B", "bike B AY1 K", "motorcycle M OW1 T ER0 S AY2 K AH0 L", "boat B OW1 T", "ship SH IH1 P",
    "plane P L EY1 N", "jet JH EH1 T", "train T R EY1 N", "sedan S AH0 D AE1 N", "coupe K UW1 P",
    "convertible K AH0 N V ER1 T AH0 B AH0 L", "pickup P IH1 K AH2 P", "limo L IH1 M OW0", "limousine L IH1 M AH0 Z IY2 N",
    "ambulance AE1 M B Y AH0 L AH0 N S", "engine EH1 N JH AH0 N", "wheel W IY1 L", "wheels W IY1 L Z",
    "tire T AY1 ER0", "tires T AY1 ER0 Z", "gas G AE1 S", "fuel F Y UW1 AH0 L", "speed S P IY1 D",
    "garage G ER0 AA1 ZH", "parking P AA1 R K IH0 NG", "traffic T R AE1 F IH0 K", "road R OW1 D", "roads R OW1 D Z",
    "highway HH AY1 W EY2", "freeway F R IY1 W EY2", "bridge B R IH1 JH", "tunnel T AH1 N AH0 L", "lane L EY1 N",
    "drive D R AY1 V", "driver D R AY1 V ER0", "ride R AY1 D", "trip T R IH1 P", "route R UW1 T", "map M AE1 P",
    "gps JH IY1 P IY1 EH1 S", "seat S IY1 T", "door D AO1 R", "doors D AO1 R Z", "trunk T R AH1 NG K",
    "window W IH1 N D OW0", "horn HH AO1 R N", "brake B R EY1 K", "brakes B R EY1 K S", "wreck R EH1 K",
    "accident AE1 K S AH0 D AH0 N T", "crash K R AE1 SH", "gear G IH1 R", "mile M AY1 L", "miles M AY1 L Z",
    "mph EH1 M P IY1 EY1 CH", "fast F AE1 S T", "faster F AE1 S T ER0", "slow S L OW1", "slower S L OW1 ER0",

    // ---- places and the city
    "city S IH1 T IY0", "town T AW1 N", "state S T EY1 T", "country K AH1 N T R IY0", "world W ER1 L D",
    "place P L EY1 S", "house HH AW1 S", "houses HH AW1 Z IH0 Z", "home HH OW1 M", "room R UW1 M",
    "apartment AH0 P AA1 R T M AH0 N T", "building B IH1 L D IH0 NG", "office AO1 F AH0 S", "store S T AO1 R",
    "shop SH AA1 P", "mall M AO1 L", "market M AA1 R K AH0 T", "restaurant R EH1 S T ER0 AA2 N T",
    "diner D AY1 N ER0", "cafe K AH0 F EY1", "bar B AA1 R", "club K L AH1 B", "nightclub N AY1 T K L AH2 B",
    "casino K AH0 S IY1 N OW0", "hotel HH OW0 T EH1 L", "motel M OW0 T EH1 L", "hospital HH AA1 S P IH2 T AH0 L",
    "school S K UW1 L", "church CH ER1 CH", "airport EH1 R P AO2 R T", "station S T EY1 SH AH0 N",
    "park P AA1 R K", "beach B IY1 CH", "beaches B IY1 CH IH0 Z", "ocean OW1 SH AH0 N", "sea S IY1",
    "island AY1 L AH0 N D", "coast K OW1 S T", "shore SH AO1 R", "harbor HH AA1 R B ER0", "port P AO1 R T",
    "dock D AA1 K", "docks D AA1 K S", "pier P IH1 R", "bay B EY1", "river R IH1 V ER0", "lake L EY1 K",
    "swamp S W AA1 M P", "forest F AO1 R AH0 S T", "hill HH IH1 L", "hills HH IH1 L Z", "mountain M AW1 N T AH0 N",
    "desert D EH1 Z ER0 T", "farm F AA1 R M", "field F IY1 L D", "north N AO1 R TH", "south S AW1 TH",
    "east IY1 S T", "west W EH1 S T", "northern N AO1 R DH ER0 N", "southern S AH1 DH ER0 N", "eastern IY1 S T ER0 N",
    "western W EH1 S T ER0 N", "avenue AE1 V AH0 N UW2", "boulevard B UH1 L AH0 V AA2 R D", "block B L AA1 K",
    "neighborhood N EY1 B ER0 HH UH2 D", "roof R UW1 F", "floor F L AO1 R", "stairs S T EH1 R Z",
    "elevator EH1 L AH0 V EY2 T ER0", "wall W AO1 L", "gate G EY1 T", "fence F EH1 N S", "yard Y AA1 R D",
    "kitchen K IH1 CH AH0 N", "bathroom B AE1 TH R UW2 M", "bedroom B EH1 D R UW2 M", "basement B EY1 S M AH0 N T",
    "warehouse W EH1 R HH AW2 S", "factory F AE1 K T ER0 IY0", "mansion M AE1 N SH AH0 N", "penthouse P EH1 N T HH AW2 S",
    "tower T AW1 ER0", "downtown D AW1 N T AW1 N", "suburbs S AH1 B ER0 B Z", "airport EH1 R P AO2 R T",
    "america AH0 M EH1 R AH0 K AH0", "american AH0 M EH1 R AH0 K AH0 N", "miami M AY0 AE1 M IY0",
    "florida F L AO1 R AH0 D AH0", "mexico M EH1 K S IH0 K OW2", "cuba K Y UW1 B AH0", "havana HH AH0 V AE1 N AH0",
    "vegas V EY1 G AH0 S", "york Y AO1 R K", "angeles AE1 N JH AH0 L AH0 S",
    // game world names
    "porto P AO1 R T OW2", "sol S OW1 L", "palmera P AA0 L M EH1 R AH0", "sawgrass S AO1 G R AE2 S",
    "coral K AO1 R AH0 L", "keys K IY1 Z", "cypress S AY1 P R AH0 S", "ridge R IH1 JH",
    "okahatchee OW2 K AH0 HH AE1 CH IY0", "fort F AO1 R T", "castell K AE0 S T EH1 L", "neon N IY1 AA0 N",
    "tide T AY1 D", "vice V AY1 S",

    // ---- things
    "thing TH IH1 NG", "things TH IH1 NG Z", "stuff S T AH1 F", "way W EY1", "part P AA1 R T", "side S AY1 D",
    "kind K AY1 N D", "sort S AO1 R T", "type T AY1 P", "piece P IY1 S", "bit B IH1 T", "end EH1 N D",
    "top T AA1 P", "bottom B AA1 T AH0 M", "middle M IH1 D AH0 L", "center S EH1 N T ER0", "edge EH1 JH",
    "line L AY1 N", "point P OY1 N T", "word W ER1 D", "words W ER1 D Z", "name N EY1 M", "story S T AO1 R IY0",
    "question K W EH1 S CH AH0 N", "answer AE1 N S ER0", "idea AY0 D IY1 AH0", "reason R IY1 Z AH0 N",
    "fact F AE1 K T", "truth T R UW1 TH", "lie L AY1", "lies L AY1 Z", "secret S IY1 K R AH0 T", "plan P L AE1 N",
    "chance CH AE1 N S", "choice CH OY1 S", "luck L AH1 K", "mistake M IH0 S T EY1 K", "sense S EH1 N S",
    "power P AW1 ER0", "war W AO1 R", "peace P IY1 S", "fight F AY1 T", "game G EY1 M", "games G EY1 M Z",
    "sport S P AO1 R T", "team T IY1 M", "player P L EY1 ER0", "music M Y UW1 Z IH0 K", "song S AO1 NG",
    "songs S AO1 NG Z", "radio R EY1 D IY0 OW2", "news N UW1 Z", "movie M UW1 V IY0", "show SH OW1",
    "picture P IH1 K CH ER0", "photo F OW1 T OW2", "camera K AE1 M ER0 AH0", "video V IH1 D IY0 OW0",
    "phone F OW1 N", "cellphone S EH1 L F OW2 N", "message M EH1 S AH0 JH", "letter L EH1 T ER0",
    "paper P EY1 P ER0", "book B UH1 K", "magazine M AE1 G AH0 Z IY2 N", "computer K AH0 M P Y UW1 T ER0",
    "internet IH1 N T ER0 N EH2 T", "email IY1 M EY2 L", "tv T IY1 V IY1", "television T EH1 L AH0 V IH2 ZH AH0 N",
    "key K IY1", "keys K IY1 Z", "bag B AE1 G", "box B AA1 K S", "bottle B AA1 T AH0 L", "glass G L AE1 S",
    "cup K AH1 P", "table T EY1 B AH0 L", "chair CH EH1 R", "bed B EH1 D", "couch K AW1 CH", "light L AY1 T",
    "lights L AY1 T S", "clothes K L OW1 DH Z", "shirt SH ER1 T", "jacket JH AE1 K AH0 T", "suit S UW1 T",
    "dress D R EH1 S", "shoes SH UW1 Z", "hat HH AE1 T", "mask M AE1 S K", "glasses G L AE1 S IH0 Z",
    "ring R IH1 NG", "chain CH EY1 N", "rope R OW1 P", "tool T UW1 L", "tools T UW1 L Z", "ticket T IH1 K AH0 T",
    "tickets T IH1 K AH0 T S", "card K AA1 R D", "gift G IH1 F T", "present P R EH1 Z AH0 N T", "prize P R AY1 Z",
    "food F UW1 D", "water W AO1 T ER0", "coffee K AA1 F IY0", "tea T IY1", "beer B IH1 R", "wine W AY1 N",
    "whiskey W IH1 S K IY0", "vodka V AA1 D K AH0", "rum R AH1 M", "drink D R IH1 NG K", "drinks D R IH1 NG K S",
    "soda S OW1 D AH0", "juice JH UW1 S", "milk M IH1 L K", "pizza P IY1 T S AH0", "burger B ER1 G ER0",
    "sandwich S AE1 N D W IH0 CH", "chicken CH IH1 K AH0 N", "meat M IY1 T", "fish F IH1 SH", "bread B R EH1 D",
    "breakfast B R EH1 K F AH0 S T", "lunch L AH1 N CH", "dinner D IH1 N ER0", "meal M IY1 L", "taco T AA1 K OW0",
    "tacos T AA1 K OW0 Z", "fries F R AY1 Z", "cheese CH IY1 Z", "sugar SH UH1 G ER0", "salt S AO1 L T",
    "cigarette S IH2 G ER0 EH1 T", "smoke S M OW1 K", "weed W IY1 D", "animal AE1 N AH0 M AH0 L", "dog D AO1 G",
    "dogs D AO1 G Z", "cat K AE1 T", "bird B ER1 D", "horse HH AO1 R S", "shark SH AA1 R K", "alligator AE1 L AH0 G EY2 T ER0",
    "gator G EY1 T ER0", "snake S N EY1 K", "sun S AH1 N", "moon M UW1 N", "star S T AA1 R", "stars S T AA1 R Z",
    "sky S K AY1", "cloud K L AW1 D", "clouds K L AW1 D Z", "weather W EH1 DH ER0", "storm S T AO1 R M",
    "hurricane HH ER1 AH0 K EY2 N", "wind W IH1 N D", "heat HH IY1 T", "fog F AA1 G", "snow S N OW1",
    "air EH1 R", "earth ER1 TH", "ground G R AW1 N D", "tree T R IY1", "trees T R IY1 Z", "palm P AA1 M",
    "palms P AA1 M Z", "flower F L AW1 ER0", "grass G R AE1 S", "sand S AE1 N D", "wave W EY1 V", "waves W EY1 V Z",
    "rock R AA1 K", "stone S T OW1 N", "metal M EH1 T AH0 L", "wood W UH1 D", "color K AH1 L ER0",
    "colors K AH1 L ER0 Z", "sound S AW1 N D", "noise N OY1 Z", "smell S M EH1 L", "taste T EY1 S T",
    "company K AH1 M P AH0 N IY0", "job JH AA1 B", "work W ER1 K", "boss B AO1 S", "meeting M IY1 T IH0 NG",
    "party P AA1 R T IY0", "event IH0 V EH1 N T", "concert K AA1 N S ER0 T", "festival F EH1 S T AH0 V AH0 L",
    "hit HH IH1 T", "hits HH IH1 T S", "station S T EY1 SH AH0 N", "caller K AO1 L ER0", "listener L IH1 S AH0 N ER0",
    "listeners L IH1 S AH0 N ER0 Z", "request R IH0 K W EH1 S T", "requests R IH0 K W EH1 S T S", "dj D IY1 JH EY1",
    "sale S EY1 L", "discount D IH1 S K AW0 N T", "offer AO1 F ER0", "deal D IY1 L", "deals D IY1 L Z",
    "brand B R AE1 N D", "product P R AA1 D AH0 K T", "insurance IH0 N SH UH1 R AH0 N S", "injury IH1 N JH ER0 IY0",
    "forecast F AO1 R K AE2 S T", "temperature T EH1 M P R AH0 CH ER0", "degrees D IH0 G R IY1 Z",
    "degree D IH0 G R IY1", "update AH1 P D EY2 T", "headline HH EH1 D L AY2 N", "headlines HH EH1 D L AY2 N Z",
    "report R IH0 P AO1 R T", "mayor M EY1 ER0", "governor G AH1 V ER0 N ER0", "president P R EH1 Z AH0 D AH0 N T",
    "government G AH1 V ER0 N M AH0 N T", "election IH0 L EH1 K SH AH0 N", "economy IH0 K AA1 N AH0 M IY0",
    "tourist T UH1 R IH0 S T", "tourists T UH1 R IH0 S T S", "sponsor S P AA1 N S ER0", "sponsored S P AA1 N S ER0 D",
    "commercial K AH0 M ER1 SH AH0 L", "channel CH AE1 N AH0 L", "program P R OW1 G R AE2 M", "episode EH1 P AH0 S OW2 D",
    "fan F AE1 N", "fans F AE1 N Z", "star S T AA1 R", "celebrity S AH0 L EH1 B R AH0 T IY0",

    // ---- abstract / general nouns
    "people P IY1 P AH0 L", "problem P R AA1 B L AH0 M", "system S IH1 S T AH0 M", "program P R OW1 G R AE2 M",
    "government G AH1 V ER0 N M AH0 N T", "area EH1 R IY0 AH0", "fact F AE1 K T", "group G R UW1 P",
    "issue IH1 SH UW0", "service S ER1 V AH0 S", "member M EH1 M B ER0", "level L EH1 V AH0 L", "office AO1 F AH0 S",
    "history HH IH1 S T ER0 IY0", "result R IH0 Z AH1 L T", "change CH EY1 N JH", "moment M OW1 M AH0 N T",
    "information IH2 N F ER0 M EY1 SH AH0 N", "education EH2 JH AH0 K EY1 SH AH0 N", "experience IH0 K S P IH1 R IY0 AH0 N S",
    "effect IH0 F EH1 K T", "class K L AE1 S", "control K AH0 N T R OW1 L", "care K EH1 R", "role R OW1 L",
    "rate R EY1 T", "value V AE1 L Y UW0", "action AE1 K SH AH0 N", "model M AA1 D AH0 L", "position P AH0 Z IH1 SH AH0 N",
    "record R EH1 K ER0 D", "space S P EY1 S", "form F AO1 R M", "matter M AE1 T ER0", "situation S IH2 CH UW0 EY1 SH AH0 N",
    "practice P R AE1 K T IH0 S", "attention AH0 T EH1 N SH AH0 N", "relationship R IY0 L EY1 SH AH0 N SH IH2 P",
    "future F Y UW1 CH ER0", "decision D IH0 S IH1 ZH AH0 N", "interest IH1 N T R AH0 S T", "love L AH1 V",
    "hate HH EY1 T", "fear F IH1 R", "hope HH OW1 P", "pain P EY1 N", "fun F AH1 N", "joke JH OW1 K",
    "favor F EY1 V ER0", "promise P R AA1 M AH0 S", "rule R UW1 L", "rules R UW1 L Z", "deal D IY1 L",
    "danger D EY1 N JH ER0", "safety S EY1 F T IY0", "freedom F R IY1 D AH0 M", "dream D R IY1 M",
    "memory M EH1 M ER0 IY0", "nature N EY1 CH ER0", "science S AY1 AH0 N S", "art AA1 R T", "culture K AH1 L CH ER0",
    "style S T AY1 L", "language L AE1 NG G W AH0 JH", "english IH1 NG G L IH0 SH", "spanish S P AE1 N IH0 SH",
    "chance CH AE1 N S", "reputation R EH2 P Y AH0 T EY1 SH AH0 N", "respect R IH0 S P EH1 K T", "honor AA1 N ER0",
    "pride P R AY1 D", "shame SH EY1 M", "glory G L AO1 R IY0", "success S AH0 K S EH1 S", "failure F EY1 L Y ER0",
    "mission M IH1 SH AH0 N", "target T AA1 R G AH0 T", "goal G OW1 L", "opportunity AA2 P ER0 T UW1 N AH0 T IY0",
    "paradise P EH1 R AH0 D AY2 S", "vacation V EY0 K EY1 SH AH0 N", "holiday HH AA1 L AH0 D EY2",
    "adventure AE0 D V EH1 N CH ER0", "welcome W EH1 L K AH0 M",

    // ---- adjectives
    "good G UH1 D", "better B EH1 T ER0", "best B EH1 S T", "bad B AE1 D", "worse W ER1 S", "worst W ER1 S T",
    "new N UW1", "old OW1 L D", "older OW1 L D ER0", "young Y AH1 NG", "big B IH1 G", "small S M AO1 L",
    "little L IH1 T AH0 L", "large L AA1 R JH", "long L AO1 NG", "short SH AO1 R T", "tall T AO1 L",
    "high HH AY1", "low L OW1", "great G R EY1 T", "important IH0 M P AO1 R T AH0 N T", "different D IH1 F ER0 AH0 N T",
    "same S EY1 M", "next N EH1 K S T", "last L AE1 S T", "able EY1 B AH0 L", "free F R IY1", "true T R UW1",
    "false F AO1 L S", "full F UH1 L", "empty EH1 M P T IY0", "special S P EH1 SH AH0 L", "easy IY1 Z IY0",
    "hard HH AA1 R D", "difficult D IH1 F AH0 K AH0 L T", "clear K L IH1 R", "certain S ER1 T AH0 N",
    "open OW1 P AH0 N", "closed K L OW1 Z D", "private P R AY1 V AH0 T", "public P AH1 B L IH0 K",
    "real R IY1 L", "fake F EY1 K", "wrong R AO1 NG", "right R AY1 T", "fine F AY1 N", "nice N AY1 S",
    "cool K UW1 L", "hot HH AA1 T", "cold K OW1 L D", "warm W AO1 R M", "dead D EH1 D", "alive AH0 L AY1 V",
    "happy HH AE1 P IY0", "sad S AE1 D", "angry AE1 NG G R IY0", "mad M AE1 D", "crazy K R EY1 Z IY0",
    "insane IH0 N S EY1 N", "stupid S T UW1 P AH0 D", "dumb D AH1 M", "smart S M AA1 R T", "funny F AH1 N IY0",
    "serious S IH1 R IY0 AH0 S", "ready R EH1 D IY0", "simple S IH1 M P AH0 L", "strong S T R AO1 NG",
    "weak W IY1 K", "safe S EY1 F", "quiet K W AY1 AH0 T", "loud L AW1 D", "quick K W IH1 K", "slow S L OW1",
    "beautiful B Y UW1 T AH0 F AH0 L", "pretty P R IH1 T IY0", "ugly AH1 G L IY0", "rich R IH1 CH",
    "cheap CH IY1 P", "expensive IH0 K S P EH1 N S IH0 V", "dirty D ER1 T IY0", "clean K L IY1 N",
    "fresh F R EH1 SH", "sweet S W IY1 T", "sorry S AA1 R IY0", "lucky L AH1 K IY0", "busy B IH1 Z IY0",
    "heavy HH EH1 V IY0", "whole HH OW1 L", "wild W AY1 L D", "perfect P ER1 F IH0 K T", "scared S K EH1 R D",
    "afraid AH0 F R EY1 D", "tired T AY1 ER0 D", "hungry HH AH1 NG G R IY0", "sick S IH1 K", "hurt HH ER1 T",
    "dark D AA1 R K", "bright B R AY1 T", "black B L AE1 K", "white W AY1 T", "red R EH1 D", "blue B L UW1",
    "green G R IY1 N", "yellow Y EH1 L OW0", "brown B R AW1 N", "orange AO1 R AH0 N JH", "purple P ER1 P AH0 L",
    "pink P IH1 NG K", "gray G R EY1", "grey G R EY1", "silver S IH1 L V ER0", "golden G OW1 L D AH0 N",
    "main M EY1 N", "final F AY1 N AH0 L", "huge HH Y UW1 JH", "tiny T AY1 N IY0", "entire IH0 N T AY1 ER0",
    "close K L OW1 S", "far F AA1 R", "local L OW1 K AH0 L", "national N AE1 SH AH0 N AH0 L", "personal P ER1 S AH0 N AH0 L",
    "common K AA1 M AH0 N", "popular P AA1 P Y AH0 L ER0", "famous F EY1 M AH0 S", "legal L IY1 G AH0 L",
    "illegal IH2 L IY1 G AH0 L", "normal N AO1 R M AH0 L", "strange S T R EY1 N JH", "weird W IH1 R D",
    "awesome AO1 S AH0 M", "amazing AH0 M EY1 Z IH0 NG", "incredible IH2 N K R EH1 D AH0 B AH0 L",
    "terrible T EH1 R AH0 B AH0 L", "horrible HH AO1 R AH0 B AH0 L", "wonderful W AH1 N D ER0 F AH0 L",
    "fantastic F AE0 N T AE1 S T IH0 K", "excellent EH1 K S AH0 L AH0 N T", "lovely L AH1 V L IY0",
    "gorgeous G AO1 R JH AH0 S", "sunny S AH1 N IY0", "cloudy K L AW1 D IY0", "rainy R EY1 N IY0",
    "windy W IH1 N D IY0", "humid HH Y UW1 M AH0 D", "tropical T R AA1 P IH0 K AH0 L", "sexy S EH1 K S IY0",
    "tough T AH1 F", "sharp SH AA1 R P", "smooth S M UW1 DH", "soft S AO1 F T", "deep D IY1 P", "wide W AY1 D",
    "thick TH IH1 K", "thin TH IH1 N", "flat F L AE1 T", "round R AW1 N D", "square S K W EH1 R", "straight S T R EY1 T",
    "nervous N ER1 V AH0 S", "calm K AA1 M", "proud P R AW1 D", "honest AA1 N AH0 S T", "guilty G IH1 L T IY0",
    "missing M IH1 S IH0 NG", "late L EY1 T", "early ER1 L IY0", "recent R IY1 S AH0 N T", "current K ER1 AH0 N T",
    "available AH0 V EY1 L AH0 B AH0 L", "likely L AY1 K L IY0", "various V EH1 R IY0 AH0 S",
    "several S EH1 V R AH0 L", "extra EH1 K S T R AH0", "total T OW1 T AH0 L", "exact IH0 G Z AE1 K T",
    "official AH0 F IH1 SH AH0 L", "international IH2 N T ER0 N AE1 SH AH0 N AH0 L", "major M EY1 JH ER0",
    "minor M AY1 N ER0", "military M IH1 L AH0 T EH2 R IY0", "medical M EH1 D AH0 K AH0 L",
    "physical F IH1 Z IH0 K AH0 L", "general JH EH1 N ER0 AH0 L", "social S OW1 SH AH0 L", "political P AH0 L IH1 T AH0 K AH0 L",
    "federal F EH1 D ER0 AH0 L", "natural N AE1 CH ER0 AH0 L", "human HH Y UW1 M AH0 N", "hot HH AA1 T",

    // ---- more high-frequency words (mixed classes)
    "about ~AH0 B AW1 T", "word W ER1 D", "water W AO1 T ER0", "people P IY1 P AH0 L", "write R AY1 T",
    "number N AH1 M B ER0", "sound S AW1 N D", "place P L EY1 S", "year Y IH1 R", "show SH OW1", "every EH1 V R IY0",
    "name N EY1 M", "good G UH1 D", "sentence S EH1 N T AH0 N S", "great G R EY1 T", "help HH EH1 L P",
    "through TH R UW1", "much M AH1 CH", "mean M IY1 N", "differ D IH1 F ER0", "turn T ER1 N", "cause K AO1 Z",
    "move M UW1 V", "boy B OY1", "follow F AA1 L OW0", "came K EY1 M", "want W AA1 N T", "form F AO1 R M",
    "small S M AO1 L", "set S EH1 T", "put P UH1 T", "end EH1 N D", "large L AA1 R JH", "spell S P EH1 L",
    "add AE1 D", "land L AE1 N D", "here HH IH1 R", "must ~M AH0 S T", "high HH AY1", "such ~S AH0 CH",
    "why W AY1", "ask AE1 S K", "went W EH1 N T", "read R IY1 D", "need N IY1 D", "house HH AW1 S",
    "picture P IH1 K CH ER0", "try T R AY1", "again AH0 G EH1 N", "animal AE1 N AH0 M AH0 L", "study S T AH1 D IY0",
    "learn L ER1 N", "should ~SH UH0 D", "world W ER1 L D", "high HH AY1", "every EH1 V R IY0", "near N IH1 R",
    "own OW1 N", "below B IH0 L OW1", "country K AH1 N T R IY0", "plant P L AE1 N T", "last L AE1 S T",
    "school S K UW1 L", "father F AA1 DH ER0", "keep K IY1 P", "tree T R IY1", "never N EH1 V ER0",
    "start S T AA1 R T", "city S IH1 T IY0", "earth ER1 TH", "eye AY1", "light L AY1 T", "thought TH AO1 T",
    "head HH EH1 D", "under AH1 N D ER0", "story S T AO1 R IY0", "saw S AO1", "left L EH1 F T",
    "few F Y UW1", "while W AY1 L", "along AH0 L AO1 NG", "might ~M AY0 T", "close K L OW1 Z",
    "something S AH1 M TH IH0 NG", "seem S IY1 M", "next N EH1 K S T", "hard HH AA1 R D", "open OW1 P AH0 N",
    "example IH0 G Z AE1 M P AH0 L", "begin B IH0 G IH1 N", "life L AY1 F", "always AO1 L W EY2 Z",
    "those ~DH OW0 Z", "both B OW1 TH", "paper P EY1 P ER0", "together T AH0 G EH1 DH ER0", "got G AA1 T",
    "group G R UW1 P", "often AO1 F AH0 N", "run R AH1 N", "important IH0 M P AO1 R T AH0 N T", "until AH0 N T IH1 L",
    "children CH IH1 L D R AH0 N", "side S AY1 D", "feet F IY1 T", "car K AA1 R", "mile M AY1 L", "night N AY1 T",
    "walk W AO1 K", "white W AY1 T", "sea S IY1", "began B IH0 G AE1 N", "grow G R OW1", "took T UH1 K",
    "river R IH1 V ER0", "four F AO1 R", "carry K AE1 R IY0", "state S T EY1 T", "once W AH1 N S",
    "book B UH1 K", "hear HH IH1 R", "stop S T AA1 P", "without W IH0 TH AW1 T", "second S EH1 K AH0 N D",
    "late L EY1 T", "miss M IH1 S", "idea AY0 D IY1 AH0", "enough IH0 N AH1 F", "eat IY1 T", "face F EY1 S",
    "watch W AA1 CH", "far F AA1 R", "indian IH1 N D IY0 AH0 N", "really R IH1 L IY0", "almost AO1 L M OW2 S T",
    "let L EH1 T", "above AH0 B AH1 V", "girl G ER1 L", "sometimes S AH0 M T AY1 M Z", "mountains M AW1 N T AH0 N Z",
    "cut K AH1 T", "young Y AH1 NG", "talk T AO1 K", "soon S UW1 N", "list L IH1 S T", "song S AO1 NG",
    "being B IY1 IH0 NG", "leave L IY1 V", "family F AE1 M AH0 L IY0", "it's ~IH0 T S", "body B AA1 D IY0",
    "music M Y UW1 Z IH0 K", "color K AH1 L ER0", "stand S T AE1 N D", "sun S AH1 N", "questions K W EH1 S CH AH0 N Z",
    "fish F IH1 SH", "area EH1 R IY0 AH0", "mark M AA1 R K", "dog D AO1 G", "horse HH AO1 R S", "birds B ER1 D Z",
    "problem P R AA1 B L AH0 M", "complete K AH0 M P L IY1 T", "room R UW1 M", "knew N UW1", "since S IH1 N S",
    "ever EH1 V ER0", "piece P IY1 S", "told T OW1 L D", "usually Y UW1 ZH AH0 W AH0 L IY0", "didn't D IH1 D AH0 N T",
    "friends F R EH1 N D Z", "easy IY1 Z IY0", "heard HH ER1 D", "order AO1 R D ER0", "red R EH1 D",
    "door D AO1 R", "sure SH UH1 R", "become B IH0 K AH1 M", "top T AA1 P", "ship SH IH1 P", "across AH0 K R AO1 S",
    "today T AH0 D EY1", "during D UH1 R IH0 NG", "short SH AO1 R T", "better B EH1 T ER0", "best B EH1 S T",
    "however HH AW0 EH1 V ER0", "low L OW1", "hours AW1 ER0 Z", "black B L AE1 K", "products P R AA1 D AH0 K T S",
    "happened HH AE1 P AH0 N D", "whole HH OW1 L", "measure M EH1 ZH ER0", "remember R IH0 M EH1 M B ER0",
    "early ER1 L IY0", "waves W EY1 V Z", "reached R IY1 CH T", "listen L IH1 S AH0 N", "wind W IH1 N D",
    "rock R AA1 K", "space S P EY1 S", "covered K AH1 V ER0 D", "fast F AE1 S T", "several S EH1 V R AH0 L",
    "hold HH OW1 L D", "himself HH IH0 M S EH1 L F", "toward T AH0 W AO1 R D", "five F AY1 V", "step S T EH1 P",
    "morning M AO1 R N IH0 NG", "passed P AE1 S T", "vowel V AW1 AH0 L", "true T R UW1", "hundred HH AH1 N D R AH0 D",
    "against AH0 G EH1 N S T", "pattern P AE1 T ER0 N", "numeral N UW1 M ER0 AH0 L", "table T EY1 B AH0 L",
    "north N AO1 R TH", "slowly S L OW1 L IY0", "money M AH1 N IY0", "map M AE1 P", "farm F AA1 R M",
    "pulled P UH1 L D", "draw D R AO1", "voice V OY1 S", "seen S IY1 N", "cold K OW1 L D", "cried K R AY1 D",
    "plan P L AE1 N", "notice N OW1 T AH0 S", "south S AW1 TH", "sing S IH1 NG", "war W AO1 R", "ground G R AW1 N D",
    "fall F AO1 L", "king K IH1 NG", "town T AW1 N", "i'll ~AY1 L", "unit Y UW1 N AH0 T", "figure F IH1 G Y ER0",
    "certain S ER1 T AH0 N", "field F IY1 L D", "travel T R AE1 V AH0 L", "wood W UH1 D", "fire F AY1 ER0",
    "upon ~AH0 P AA1 N", "done D AH1 N", "english IH1 NG G L IH0 SH", "road R OW1 D", "half HH AE1 F",
    "ten T EH1 N", "fly F L AY1", "gave G EY1 V", "box B AA1 K S", "finally F AY1 N AH0 L IY0", "wait W EY1 T",
    "correct K ER0 EH1 K T", "oh OW1", "quickly K W IH1 K L IY0", "person P ER1 S AH0 N", "became B IH0 K EY1 M",
    "shown SH OW1 N", "minutes M IH1 N AH0 T S", "strong S T R AO1 NG", "verb V ER1 B", "stars S T AA1 R Z",
    "front F R AH1 N T", "feel F IY1 L", "fact F AE1 K T", "inches IH1 N CH IH0 Z", "street S T R IY1 T",
    "decided D IH0 S AY1 D IH0 D", "contain K AH0 N T EY1 N", "course K AO1 R S", "surface S ER1 F AH0 S",
    "produce P R AH0 D UW1 S", "building B IH1 L D IH0 NG", "ocean OW1 SH AH0 N", "class K L AE1 S",
    "note N OW1 T", "nothing N AH1 TH IH0 NG", "rest R EH1 S T", "carefully K EH1 R F AH0 L IY0",
    "scientists S AY1 AH0 N T IH0 S T S", "inside IH0 N S AY1 D", "wheels W IY1 L Z", "stay S T EY1",
    "green G R IY1 N", "known N OW1 N", "island AY1 L AH0 N D", "week W IY1 K", "less L EH1 S", "machine M AH0 SH IY1 N",
    "base B EY1 S", "ago AH0 G OW1", "stood S T UH1 D", "plane P L EY1 N", "system S IH1 S T AH0 M",
    "behind B IH0 HH AY1 N D", "ran R AE1 N", "round R AW1 N D", "boat B OW1 T", "game G EY1 M", "force F AO1 R S",
    "brought B R AO1 T", "understand AH2 N D ER0 S T AE1 N D", "warm W AO1 R M", "common K AA1 M AH0 N",
    "bring B R IH1 NG", "explain IH0 K S P L EY1 N", "dry D R AY1", "though DH OW1", "language L AE1 NG G W AH0 JH",
    "shape SH EY1 P", "deep D IY1 P", "thousands TH AW1 Z AH0 N D Z", "yes Y EH1 S", "clear K L IH1 R",
    "equation IH0 K W EY1 ZH AH0 N", "yet Y EH1 T", "government G AH1 V ER0 N M AH0 N T", "filled F IH1 L D",
    "heat HH IY1 T", "full F UH1 L", "hot HH AA1 T", "check CH EH1 K", "object AA1 B JH EH0 K T", "am ~AE0 M",
    "rule R UW1 L", "among AH0 M AH1 NG", "noun N AW1 N", "power P AW1 ER0", "cannot K AE1 N AA0 T",
    "able EY1 B AH0 L", "six S IH1 K S", "size S AY1 Z", "dark D AA1 R K", "ball B AO1 L", "material M AH0 T IH1 R IY0 AH0 L",
    "special S P EH1 SH AH0 L", "heavy HH EH1 V IY0", "fine F AY1 N", "pair P EH1 R", "circle S ER1 K AH0 L",
    "include IH0 N K L UW1 D", "built B IH1 L T", "can't K AE1 N T", "matter M AE1 T ER0", "square S K W EH1 R",
    "syllables S IH1 L AH0 B AH0 L Z", "perhaps P ER0 HH AE1 P S", "bill B IH1 L", "felt F EH1 L T",
    "suddenly S AH1 D AH0 N L IY0", "test T EH1 S T", "direction D ER0 EH1 K SH AH0 N", "center S EH1 N T ER0",
    "farmers F AA1 R M ER0 Z", "ready R EH1 D IY0", "anything EH1 N IY0 TH IH2 NG", "divided D IH0 V AY1 D IH0 D",
    "general JH EH1 N ER0 AH0 L", "energy EH1 N ER0 JH IY0", "subject S AH1 B JH IH0 K T", "europe Y UH1 R AH0 P",
    "moon M UW1 N", "region R IY1 JH AH0 N", "return R IH0 T ER1 N", "believe B IH0 L IY1 V", "dance D AE1 N S",
    "members M EH1 M B ER0 Z", "picked P IH1 K T", "simple S IH1 M P AH0 L", "cells S EH1 L Z", "paint P EY1 N T",
    "mind M AY1 N D", "love L AH1 V", "cause K AO1 Z", "rain R EY1 N", "exercise EH1 K S ER0 S AY2 Z",
    "eggs EH1 G Z", "train T R EY1 N", "blue B L UW1", "wish W IH1 SH", "drop D R AA1 P", "developed D IH0 V EH1 L AH0 P T",
    "window W IH1 N D OW0", "difference D IH1 F ER0 AH0 N S", "distance D IH1 S T AH0 N S", "heart HH AA1 R T",
    "site S AY1 T", "sum S AH1 M", "summer S AH1 M ER0", "wall W AO1 L", "forest F AO1 R AH0 S T",
    "probably P R AA1 B AH0 B L IY0", "legs L EH1 G Z", "sat S AE1 T", "main M EY1 N", "winter W IH1 N T ER0",
    "wide W AY1 D", "written R IH1 T AH0 N", "length L EH1 NG K TH", "reason R IY1 Z AH0 N", "kept K EH1 P T",
    "interest IH1 N T R AH0 S T", "arms AA1 R M Z", "brother B R AH1 DH ER0", "race R EY1 S", "present P R EH1 Z AH0 N T",
    "beautiful B Y UW1 T AH0 F AH0 L", "store S T AO1 R", "job JH AA1 B", "edge EH1 JH", "past P AE1 S T",
    "sign S AY1 N", "record R EH1 K ER0 D", "finished F IH1 N IH0 SH T", "discovered D IH0 S K AH1 V ER0 D",
    "wild W AY1 L D", "happy HH AE1 P IY0", "beside B IH0 S AY1 D", "gone G AO1 N", "sky S K AY1", "grass G R AE1 S",
    "million M IH1 L Y AH0 N", "west W EH1 S T", "lay L EY1", "weather W EH1 DH ER0", "root R UW1 T",
    "instruments IH1 N S T R AH0 M AH0 N T S", "meet M IY1 T", "third TH ER1 D", "months M AH1 N TH S",
    "paragraph P EH1 R AH0 G R AE2 F", "raised R EY1 Z D", "represent R EH2 P R AH0 Z EH1 N T", "soft S AO1 F T",
    "whether ~W EH1 DH ER0", "clothes K L OW1 DH Z", "flowers F L AW1 ER0 Z", "shall ~SH AE0 L", "teacher T IY1 CH ER0",
    "held HH EH1 L D", "describe D IH0 S K R AY1 B", "drive D R AY1 V", "cross K R AO1 S", "speak S P IY1 K",
    "solve S AA1 L V", "appear AH0 P IH1 R", "metal M EH1 T AH0 L", "son S AH1 N", "either IY1 DH ER0",
    "ice AY1 S", "sleep S L IY1 P", "village V IH1 L AH0 JH", "factors F AE1 K T ER0 Z", "result R IH0 Z AH1 L T",
    "jumped JH AH1 M P T", "snow S N OW1", "ride R AY1 D", "care K EH1 R", "floor F L AO1 R", "hill HH IH1 L",
    "pushed P UH1 SH T", "baby B EY1 B IY0", "buy B AY1", "century S EH1 N CH ER0 IY0", "outside AW1 T S AY1 D",
    "everything EH1 V R IY0 TH IH2 NG", "tall T AO1 L", "already AO0 L R EH1 D IY0", "instead IH0 N S T EH1 D",
    "phrase F R EY1 Z", "soil S OY1 L", "bed B EH1 D", "copy K AA1 P IY0", "free F R IY1", "hope HH OW1 P",
    "spring S P R IH1 NG", "case K EY1 S", "laughed L AE1 F T", "nation N EY1 SH AH0 N", "quite K W AY1 T",
    "type T AY1 P", "themselves DH EH0 M S EH1 L V Z", "temperature T EH1 M P R AH0 CH ER0", "bright B R AY1 T",
    "lead L IY1 D", "everyone EH1 V R IY0 W AH2 N", "method M EH1 TH AH0 D", "section S EH1 K SH AH0 N",
    "lake L EY1 K", "iron AY1 ER0 N", "within W IH0 DH IH1 N", "dictionary D IH1 K SH AH0 N EH2 R IY0",
    "hair HH EH1 R", "age EY1 JH", "amount AH0 M AW1 N T", "scale S K EY1 L", "pounds P AW1 N D Z",
    "although AO2 L DH OW1", "per ~P ER0", "broken B R OW1 K AH0 N", "moment M OW1 M AH0 N T", "tiny T AY1 N IY0",
    "possible P AA1 S AH0 B AH0 L", "gold G OW1 L D", "milk M IH1 L K", "quiet K W AY1 AH0 T", "natural N AE1 CH ER0 AH0 L",
    "lot L AA1 T", "stone S T OW1 N", "act AE1 K T", "build B IH1 L D", "middle M IH1 D AH0 L", "speed S P IY1 D",
    "count K AW1 N T", "cat K AE1 T", "someone S AH1 M W AH2 N", "sail S EY1 L", "rolled R OW1 L D", "bear B EH1 R",
    "wonder W AH1 N D ER0", "smiled S M AY1 L D", "angle AE1 NG G AH0 L", "fraction F R AE1 K SH AH0 N",
    "africa AE1 F R IH0 K AH0", "killed K IH1 L D", "melody M EH1 L AH0 D IY0", "bottom B AA1 T AH0 M",
    "trip T R IH1 P", "hole HH OW1 L", "poor P UH1 R", "let's L EH1 T S", "fight F AY1 T", "surprise S ER0 P R AY1 Z",
    "french F R EH1 N CH", "died D AY1 D", "beat B IY1 T", "exactly IH0 G Z AE1 K T L IY0", "remain R IH0 M EY1 N",
    "dress D R EH1 S", "cat K AE1 T", "couldn't K UH1 D AH0 N T", "fingers F IH1 NG G ER0 Z", "row R OW1",
    "least L IY1 S T", "catch K AE1 CH", "climbed K L AY1 M D", "wrote R OW1 T", "shouted SH AW1 T IH0 D",
    "continued K AH0 N T IH1 N Y UW0 D", "itself IH0 T S EH1 L F", "else EH1 L S", "plains P L EY1 N Z",
    "gas G AE1 S", "england IH1 NG G L AH0 N D", "burning B ER1 N IH0 NG", "design D IH0 Z AY1 N",
    "joined JH OY1 N D", "foot F UH1 T", "law L AO1", "ears IH1 R Z", "glass G L AE1 S", "you're ~Y UH0 R",
    "grew G R UW1", "skin S K IH1 N", "valley V AE1 L IY0", "cents S EH1 N T S", "key K IY1", "president P R EH1 Z AH0 D AH0 N T",
    "brown B R AW1 N", "trouble T R AH1 B AH0 L", "cool K UW1 L", "cloud K L AW1 D", "lost L AO1 S T",
    "sent S EH1 N T", "symbols S IH1 M B AH0 L Z", "wear W EH1 R", "bad B AE1 D", "save S EY1 V",
    "experiment IH0 K S P EH1 R AH0 M AH0 N T", "engine EH1 N JH AH0 N", "alone AH0 L OW1 N", "drawing D R AO1 IH0 NG",
    "east IY1 S T", "pay P EY1", "single S IH1 NG G AH0 L", "touch T AH1 CH", "information IH2 N F ER0 M EY1 SH AH0 N",
    "express IH0 K S P R EH1 S", "mouth M AW1 TH", "yard Y AA1 R D", "equal IY1 K W AH0 L", "decimal D EH1 S AH0 M AH0 L",
    "yourself Y ER0 S EH1 L F", "control K AH0 N T R OW1 L", "practice P R AE1 K T IH0 S", "report R IH0 P AO1 R T",
    "straight S T R EY1 T", "rise R AY1 Z", "statement S T EY1 T M AH0 N T", "stick S T IH1 K", "party P AA1 R T IY0",
    "seeds S IY1 D Z", "suppose S AH0 P OW1 Z", "woman W UH1 M AH0 N", "coast K OW1 S T", "bank B AE1 NG K",
    "period P IH1 R IY0 AH0 D", "wire W AY1 ER0", "choose CH UW1 Z", "clean K L IY1 N", "visit V IH1 Z IH0 T",
    "bit B IH1 T", "whose HH UW1 Z", "received R IH0 S IY1 V D", "garden G AA1 R D AH0 N", "please P L IY1 Z",
    "strange S T R EY1 N JH", "caught K AO1 T", "fell F EH1 L", "team T IY1 M", "god G AA1 D", "captain K AE1 P T AH0 N",
    "direct D ER0 EH1 K T", "ring R IH1 NG", "serve S ER1 V", "child CH AY1 L D", "desert D EH1 Z ER0 T",
    "increase IH0 N K R IY1 S", "history HH IH1 S T ER0 IY0", "cost K AO1 S T", "maybe M EY1 B IY0",
    "business B IH1 Z N AH0 S", "separate S EH1 P ER0 EY2 T", "break B R EY1 K", "uncle AH1 NG K AH0 L",
    "hunting HH AH1 N T IH0 NG", "flow F L OW1", "lady L EY1 D IY0", "students S T UW1 D AH0 N T S",
    "human HH Y UW1 M AH0 N", "art AA1 R T", "feeling F IY1 L IH0 NG", "supply S AH0 P L AY1", "corner K AO1 R N ER0",
    "electric IH0 L EH1 K T R IH0 K", "insects IH1 N S EH2 K T S", "crops K R AA1 P S", "tone T OW1 N",
    "hit HH IH1 T", "sand S AE1 N D", "doctor D AA1 K T ER0", "provide P R AH0 V AY1 D", "thus DH AH1 S",
    "won't W OW1 N T", "cook K UH1 K", "bones B OW1 N Z", "mall M AO1 L", "board B AO1 R D", "modern M AA1 D ER0 N",
    "compound K AA1 M P AW0 N D", "mine M AY1 N", "wasn't W AA1 Z AH0 N T", "fit F IH1 T", "addition AH0 D IH1 SH AH0 N",
    "belong B IH0 L AO1 NG", "safe S EY1 F", "soldiers S OW1 L JH ER0 Z", "guess G EH1 S", "silent S AY1 L AH0 N T",
    "trade T R EY1 D", "rather R AE1 DH ER0", "compare K AH0 M P EH1 R", "crowd K R AW1 D", "poem P OW1 AH0 M",
    "enjoy EH0 N JH OY1", "elements EH1 L AH0 M AH0 N T S", "indicate IH1 N D AH0 K EY2 T", "except IH0 K S EH1 P T",
    "expect IH0 K S P EH1 K T", "flat F L AE1 T", "seven S EH1 V AH0 N", "interesting IH1 N T R AH0 S T IH0 NG",
    "sense S EH1 N S", "string S T R IH1 NG", "blow B L OW1", "famous F EY1 M AH0 S", "value V AE1 L Y UW0",
    "wings W IH1 NG Z", "movement M UW1 V M AH0 N T", "pole P OW1 L", "exciting IH0 K S AY1 T IH0 NG",
    "branches B R AE1 N CH IH0 Z", "thick TH IH1 K", "blood B L AH1 D", "lie L AY1", "spot S P AA1 T",
    "bell B EH1 L", "fun F AH1 N", "loud L AW1 D", "consider K AH0 N S IH1 D ER0", "suggested S AH0 G JH EH1 S T IH0 D",
    "thin TH IH1 N", "position P AH0 Z IH1 SH AH0 N", "entered EH1 N T ER0 D", "fruit F R UW1 T", "tied T AY1 D",
    "rich R IH1 CH", "dollars D AA1 L ER0 Z", "send S EH1 N D", "sight S AY1 T", "chief CH IY1 F",
    "japanese JH AE2 P AH0 N IY1 Z", "stream S T R IY1 M", "planets P L AE1 N AH0 T S", "rhythm R IH1 DH AH0 M",
    "eight EY1 T", "science S AY1 AH0 N S", "major M EY1 JH ER0", "observe AH0 B Z ER1 V", "tube T UW1 B",
    "necessary N EH1 S AH0 S EH2 R IY0", "weight W EY1 T", "meat M IY1 T", "lifted L IH1 F T AH0 D",
    "process P R AA1 S EH2 S", "army AA1 R M IY0", "hat HH AE1 T", "property P R AA1 P ER0 T IY0",
    "particular P ER0 T IH1 K Y AH0 L ER0", "swim S W IH1 M", "terms T ER1 M Z", "current K ER1 AH0 N T",
    "park P AA1 R K", "sell S EH1 L", "shoulder SH OW1 L D ER0", "industry IH1 N D AH0 S T R IY0", "wash W AA1 SH",
    "block B L AA1 K", "spread S P R EH1 D", "cattle K AE1 T AH0 L", "wife W AY1 F", "sharp SH AA1 R P",
    "company K AH1 M P AH0 N IY0", "radio R EY1 D IY0 OW2", "we'll ~W IY0 L", "action AE1 K SH AH0 N",
    "capital K AE1 P AH0 T AH0 L", "factories F AE1 K T ER0 IY0 Z", "settled S EH1 T AH0 L D", "yellow Y EH1 L OW0",
    "isn't IH1 Z AH0 N T", "southern S AH1 DH ER0 N", "truck T R AH1 K", "fair F EH1 R", "printed P R IH1 N T AH0 D",
    "wouldn't W UH1 D AH0 N T", "ahead AH0 HH EH1 D", "chance CH AE1 N S", "born B AO1 R N", "level L EH1 V AH0 L",
    "triangle T R AY1 AE2 NG G AH0 L", "molecules M AA1 L AH0 K Y UW2 L Z", "france F R AE1 N S",
    "repeated R IH0 P IY1 T IH0 D", "column K AA1 L AH0 M", "western W EH1 S T ER0 N", "church CH ER1 CH",
    "sister S IH1 S T ER0", "oxygen AA1 K S AH0 JH AH0 N", "plural P L UH1 R AH0 L", "various V EH1 R IY0 AH0 S",
    "agreed AH0 G R IY1 D", "opposite AA1 P AH0 Z AH0 T", "wrong R AO1 NG", "chart CH AA1 R T",
    "prepared P R IY0 P EH1 R D", "pretty P R IH1 T IY0", "solution S AH0 L UW1 SH AH0 N", "fresh F R EH1 SH",
    "shop SH AA1 P", "suffix S AH1 F IH0 K S", "especially AH0 S P EH1 SH AH0 L IY0", "shoes SH UW1 Z",
    "actually AE1 K CH UW0 AH0 L IY0", "nose N OW1 Z", "afraid AH0 F R EY1 D", "dead D EH1 D", "sugar SH UH1 G ER0",
    "adjective AE1 JH IH0 K T IH0 V", "fig F IH1 G", "office AO1 F AH0 S", "huge HH Y UW1 JH", "gun G AH1 N",
    "similar S IH1 M AH0 L ER0", "death D EH1 TH", "score S K AO1 R", "forward F AO1 R W ER0 D", "stretched S T R EH1 CH T",
    "experience IH0 K S P IH1 R IY0 AH0 N S", "rose R OW1 Z", "allow AH0 L AW1", "fear F IH1 R", "workers W ER1 K ER0 Z",
    "washington W AA1 SH IH0 NG T AH0 N", "greek G R IY1 K", "women W IH1 M AH0 N", "bought B AO1 T", "led L EH1 D",
    "march M AA1 R CH", "northern N AO1 R DH ER0 N", "create K R IY0 EY1 T", "british B R IH1 T IH0 SH",
    "difficult D IH1 F AH0 K AH0 L T", "match M AE1 CH", "win W IH1 N", "doesn't D AH1 Z AH0 N T", "steel S T IY1 L",
    "total T OW1 T AH0 L", "deal D IY1 L", "determine D IH0 T ER1 M AH0 N", "evening IY1 V N IH0 NG", "hoe HH OW1",
    "rope R OW1 P", "cotton K AA1 T AH0 N", "apple AE1 P AH0 L", "details D IH0 T EY1 L Z", "entire IH0 N T AY1 ER0",
    "corn K AO1 R N", "substances S AH1 B S T AH0 N S IH0 Z", "smell S M EH1 L", "tools T UW1 L Z",
    "conditions K AH0 N D IH1 SH AH0 N Z", "cows K AW1 Z", "track T R AE1 K", "arrived ER0 AY1 V D",
    "located L OW1 K EY2 T IH0 D", "sir S ER1", "seat S IY1 T", "division D IH0 V IH1 ZH AH0 N", "effect IH0 F EH1 K T",
    "underline AH2 N D ER0 L AY1 N", "view V Y UW1", "anger AE1 NG G ER0", "citizen S IH1 T AH0 Z AH0 N",

    // ---- expressions, interjections, street talk
    "uh AH1", "um AH1 M", "hmm HH M", "huh HH AH1", "ah AA1", "aha AA0 HH AA1", "ooh UW1", "oops UW1 P S",
    "ouch AW1 CH", "whoa W OW1", "wow W AW1", "damn D AE1 M", "dammit D AE1 M IH0 T", "hell HH EH1 L",
    "heck HH EH1 K", "crap K R AE1 P", "shoot SH UW1 T", "gosh G AA1 SH", "geez JH IY1 Z", "jeez JH IY1 Z",
    "yo Y OW1", "cool K UW1 L", "chill CH IH1 L", "sucker S AH1 K ER0", "punk P AH1 NG K", "jerk JH ER1 K",
    "idiot IH1 D IY0 AH0 T", "moron M AO1 R AA0 N", "loser L UW1 Z ER0", "freak F R IY1 K", "psycho S AY1 K OW0",
    "maniac M EY1 N IY0 AE2 K", "lunatic L UW1 N AH0 T IH2 K", "clown K L AW1 N", "fool F UW1 L", "creep K R IY1 P",
    "pig P IH1 G", "pigs P IH1 G Z", "fuzz F AH1 Z", "five-o F AY1 V OW1", "dude D UW1 D", "man M AE1 N",
    "whatever W AH0 T EH1 V ER0", "seriously S IH1 R IY0 AH0 S L IY0", "excuse IH0 K S K Y UW1 Z",
    "congratulations K AH0 N G R AE2 CH AH0 L EY1 SH AH0 N Z", "cheers CH IH1 R Z", "bingo B IH1 NG G OW0",
    "jackpot JH AE1 K P AA2 T", "hustle HH AH1 S AH0 L", "bust B AH1 S T", "snitch S N IH1 CH", "stash S T AE1 SH",
    "ride R AY1 D", "wheels W IY1 L Z", "whip W IH1 P", "crib K R IH1 B", "dough D OW1", "benjamins B EH1 N JH AH0 M IH0 N Z",
    "shades SH EY1 D Z", "kicks K IH1 K S", "boo B UW1", "shorty SH AO1 R T IY0", "playa P L EY1 AH0",
    "gangsta G AE1 NG S T AH0", "legit L AH0 JH IH1 T", "sketchy S K EH1 CH IY0", "shady SH EY1 D IY0",
    "watch W AA1 CH", "careful K EH1 R F AH0 L", "freeze F R IY1 Z", "hands HH AE1 N D Z", "surrender S ER0 EH1 N D ER0",
    "move M UW1 V", "go G OW1", "run R AH1 N", "help HH EH1 L P", "stop S T AA1 P", "hurry HH ER1 IY0",
    "quick K W IH1 K", "quiet K W AY1 AH0 T", "shut SH AH1 T", "listen L IH1 S AH0 N",

    // ---- misc frequent words not covered above
    "able EY1 B AH0 L", "above AH0 B AH1 V", "accept AE0 K S EH1 P T", "account AH0 K AW1 N T",
    "across AH0 K R AO1 S", "activity AE0 K T IH1 V AH0 T IY0", "actor AE1 K T ER0", "address AE1 D R EH2 S",
    "adult AH0 D AH1 L T", "advice AE0 D V AY1 S", "affair AH0 F EH1 R", "age EY1 JH", "agency EY1 JH AH0 N S IY0",
    "air EH1 R", "album AE1 L B AH0 M", "amount AH0 M AW1 N T", "ancient EY1 N CH AH0 N T", "angel EY1 N JH AH0 L",
    "anger AE1 NG G ER0", "anyone EH1 N IY0 W AH2 N", "apart AH0 P AA1 R T", "apple AE1 P AH0 L",
    "argument AA1 R G Y AH0 M AH0 N T", "army AA1 R M IY0", "attempt AH0 T EH1 M P T", "audience AA1 D IY0 AH0 N S",
    "author AO1 TH ER0", "average AE1 V ER0 IH0 JH", "aware AH0 W EH1 R", "baby B EY1 B IY0", "bag B AE1 G",
    "ball B AO1 L", "band B AE1 N D", "base B EY1 S", "basic B EY1 S IH0 K", "battle B AE1 T AH0 L",
    "beer B IH1 R", "bill B IH1 L", "billion B IH1 L Y AH0 N", "birthday B ER1 TH D EY2", "blind B L AY1 N D",
    "board B AO1 R D", "border B AO1 R D ER0", "boring B AO1 R IH0 NG", "boss B AO1 S", "bottle B AA1 T AH0 L",
    "brain B R EY1 N", "brave B R EY1 V", "bread B R EH1 D", "brief B R IY1 F", "budget B AH1 JH IH0 T",
    "bunch B AH1 N CH", "burn B ER1 N", "button B AH1 T AH0 N", "cable K EY1 B AH0 L", "cake K EY1 K",
    "camp K AE1 M P", "campaign K AE0 M P EY1 N", "cancer K AE1 N S ER0", "candidate K AE1 N D AH0 D EY2 T",
    "career K ER0 IH1 R", "catch K AE1 CH", "chair CH EH1 R", "champion CH AE1 M P IY0 AH0 N",
    "character K EH1 R IH0 K T ER0", "cheap CH IY1 P", "choice CH OY1 S", "citizen S IH1 T AH0 Z AH0 N",
    "civil S IH1 V AH0 L", "classic K L AE1 S IH0 K", "coach K OW1 CH", "coat K OW1 T", "collection K AH0 L EH1 K SH AH0 N",
    "college K AA1 L IH0 JH", "comfortable K AH1 M F ER0 T AH0 B AH0 L", "community K AH0 M Y UW1 N AH0 T IY0",
    "condition K AH0 N D IH1 SH AH0 N", "conversation K AA2 N V ER0 S EY1 SH AH0 N", "cop K AA1 P",
    "couple K AH1 P AH0 L", "courage K ER1 IH0 JH", "crazy K R EY1 Z IY0", "cream K R IY1 M", "credit K R EH1 D IH0 T",
    "crowd K R AW1 D", "cute K Y UW1 T", "damage D AE1 M AH0 JH", "data D EY1 T AH0", "deadline D EH1 D L AY2 N",
    "dear D IH1 R", "debate D AH0 B EY1 T", "defense D IH0 F EH1 N S", "department D IH0 P AA1 R T M AH0 N T",
    "design D IH0 Z AY1 N", "desk D EH1 S K", "detail D IH0 T EY1 L", "device D IH0 V AY1 S", "diet D AY1 AH0 T",
    "dinner D IH1 N ER0", "dirt D ER1 T", "disease D IH0 Z IY1 Z", "doctor D AA1 K T ER0", "double D AH1 B AH0 L",
    "drama D R AA1 M AH0", "dress D R EH1 S", "duty D UW1 T IY0", "east IY1 S T", "economy IH0 K AA1 N AH0 M IY0",
    "effort EH1 F ER0 T", "egg EH1 G", "emergency IH0 M ER1 JH AH0 N S IY0", "empire EH1 M P AY2 ER0",
    "employee EH0 M P L OY1 IY0", "energy EH1 N ER0 JH IY0", "engineer EH2 N JH AH0 N IH1 R", "entrance EH1 N T R AH0 N S",
    "environment IH0 N V AY1 R AH0 N M AH0 N T", "episode EH1 P AH0 S OW2 D", "error EH1 R ER0", "event IH0 V EH1 N T",
    "exam IH0 G Z AE1 M", "exit EH1 G Z IH0 T", "expert EH1 K S P ER0 T", "eye AY1", "fair F EH1 R", "faith F EY1 TH",
    "fame F EY1 M", "fashion F AE1 SH AH0 N", "fault F AO1 L T", "favorite F EY1 V ER0 IH0 T", "feature F IY1 CH ER0",
    "fee F IY1", "film F IH1 L M", "finger F IH1 NG G ER0", "flag F L AE1 G", "flight F L AY1 T", "focus F OW1 K AH0 S",
    "football F UH1 T B AO2 L", "foreign F AO1 R AH0 N", "forever F ER0 EH1 V ER0", "fortune F AO1 R CH AH0 N",
    "frame F R EY1 M", "fuel F Y UW1 AH0 L", "fund F AH1 N D", "funeral F Y UW1 N ER0 AH0 L", "gallery G AE1 L ER0 IY0",
    "garbage G AA1 R B IH0 JH", "genius JH IY1 N Y AH0 S", "ghost G OW1 S T", "giant JH AY1 AH0 N T",
    "glad G L AE1 D", "goal G OW1 L", "golf G AA1 L F", "grade G R EY1 D", "guard G AA1 R D", "guest G EH1 S T",
    "guide G AY1 D", "habit HH AE1 B AH0 T", "hall HH AO1 L", "handsome HH AE1 N S AH0 M", "hero HH IH1 R OW0",
    "hole HH OW1 L", "honey HH AH1 N IY0", "horror HH AO1 R ER0", "host HH OW1 S T", "hotel HH OW0 T EH1 L",
    "ice AY1 S", "image IH1 M AH0 JH", "income IH1 N K AH2 M", "item AY1 T AH0 M", "jacket JH AE1 K AH0 T",
    "joy JH OY1", "junk JH AH1 NG K", "kitchen K IH1 CH AH0 N", "knowledge N AA1 L AH0 JH", "leader L IY1 D ER0",
    "lesson L EH1 S AH0 N", "level L EH1 V AH0 L", "library L AY1 B R EH2 R IY0", "list L IH1 S T",
    "loan L OW1 N", "lock L AA1 K", "machine M AH0 SH IY1 N", "magic M AE1 JH IH0 K", "manager M AE1 N IH0 JH ER0",
    "master M AE1 S T ER0", "media M IY1 D IY0 AH0", "memory M EH1 M ER0 IY0", "menu M EH1 N Y UW0",
    "message M EH1 S AH0 JH", "method M EH1 TH AH0 D", "mirror M IH1 R ER0", "model M AA1 D AH0 L",
    "mood M UW1 D", "movie M UW1 V IY0", "nation N EY1 SH AH0 N", "network N EH1 T W ER2 K", "note N OW1 T",
    "novel N AA1 V AH0 L", "nurse N ER1 S", "object AA1 B JH EH0 K T", "ocean OW1 SH AH0 N", "owner OW1 N ER0",
    "page P EY1 JH", "pain P EY1 N", "paint P EY1 N T", "pair P EH1 R", "passenger P AE1 S AH0 N JH ER0",
    "pattern P AE1 T ER0 N", "period P IH1 R IY0 AH0 D", "pilot P AY1 L AH0 T", "plastic P L AE1 S T IH0 K",
    "pleasure P L EH1 ZH ER0", "pocket P AA1 K AH0 T", "poem P OW1 AH0 M", "poison P OY1 Z AH0 N",
    "politics P AA1 L AH0 T IH2 K S", "pool P UW1 L", "pressure P R EH1 SH ER0", "prize P R AY1 Z",
    "profit P R AA1 F AH0 T", "project P R AA1 JH EH0 K T", "property P R AA1 P ER0 T IY0", "purpose P ER1 P AH0 S",
    "quality K W AA1 L AH0 T IY0", "queen K W IY1 N", "race R EY1 S", "rain R EY1 N", "range R EY1 N JH",
    "reality R IY0 AE1 L AH0 T IY0", "region R IY1 JH AH0 N", "research R IY0 S ER1 CH", "resource R IY1 S AO0 R S",
    "risk R IH1 S K", "salary S AE1 L ER0 IY0", "sample S AE1 M P AH0 L", "scene S IY1 N", "schedule S K EH1 JH UH0 L",
    "screen S K R IY1 N", "season S IY1 Z AH0 N", "seat S IY1 T", "security S IH0 K Y UH1 R AH0 T IY0",
    "series S IH1 R IY0 Z", "shape SH EY1 P", "shift SH IH1 F T", "shower SH AW1 ER0", "signal S IH1 G N AH0 L",
    "silence S AY1 L AH0 N S", "skill S K IH1 L", "sleep S L IY1 P", "smile S M AY1 L", "soldier S OW1 L JH ER0",
    "solution S AH0 L UW1 SH AH0 N", "source S AO1 R S", "speech S P IY1 CH", "spirit S P IH1 R AH0 T",
    "stage S T EY1 JH", "standard S T AE1 N D ER0 D", "status S T AE1 T AH0 S", "step S T EH1 P",
    "stock S T AA1 K", "strategy S T R AE1 T AH0 JH IY0", "stress S T R EH1 S", "student S T UW1 D AH0 N T",
    "style S T AY1 L", "subject S AH1 B JH IH0 K T", "success S AH0 K S EH1 S", "suit S UW1 T", "support S AH0 P AO1 R T",
    "surface S ER1 F AH0 S", "sweet S W IY1 T", "talent T AE1 L AH0 N T", "task T AE1 S K", "tax T AE1 K S",
    "teacher T IY1 CH ER0", "technology T EH0 K N AA1 L AH0 JH IY0", "tension T EH1 N SH AH0 N", "term T ER1 M",
    "theory TH IH1 R IY0", "ticket T IH1 K AH0 T", "tip T IH1 P", "title T AY1 T AH0 L", "topic T AA1 P IH0 K",
    "tour T UH1 R", "track T R AE1 K", "trade T R EY1 D", "tradition T R AH0 D IH1 SH AH0 N", "trial T R AY1 AH0 L",
    "trick T R IH1 K", "trust T R AH1 S T", "uniform Y UW1 N AH0 F AO2 R M", "union Y UW1 N Y AH0 N",
    "university Y UW2 N AH0 V ER1 S AH0 T IY0", "user Y UW1 Z ER0", "version V ER1 ZH AH0 N", "view V Y UW1",
    "village V IH1 L AH0 JH", "violence V AY1 AH0 L AH0 N S", "vision V IH1 ZH AH0 N", "volume V AA1 L Y UW0 M",
    "wage W EY1 JH", "weapon W EH1 P AH0 N", "wedding W EH1 D IH0 NG", "weight W EY1 T", "whale W EY1 L",
    "wine W AY1 N", "winner W IH1 N ER0", "wire W AY1 ER0", "wisdom W IH1 Z D AH0 M", "writer R AY1 T ER0",
    "youth Y UW1 TH", "zone Z OW1 N", "evil IY1 V AH0 L", "lucky L AH1 K IY0", "busy B IH1 Z IY0",
    "bye B AY1", "thanks TH AE1 NG K S", "listen L IH1 S AH0 N", "wanted W AA1 N T IH0 D", "gotta G AA1 T AH0",
    "move M UW1 V", "outta AW1 T AH0", "fella F EH1 L AH0", "tonight T AH0 N AY1 T", "cause K AO1 Z",
    "biscayne B IH0 S K EY1 N", "chevy SH EH1 V IY0", "cadillac K AE1 D AH0 L AE2 K", "ferrari F ER0 AA1 R IY0",
    "lamborghini L AE2 M B ER0 G IY1 N IY0", "porsche P AO1 R SH AH0", "mercedes M ER0 S EY1 D IY0 Z",
    "toyota T OY0 OW1 T AH0", "honda HH AA1 N D AH0", "sheriff's SH EH1 R AH0 F S", "okay OW2 K EY1",
    "suv EH1 S Y UW1 V IY1", "fbi EH1 F B IY1 AY1", "cia S IY1 AY1 EY1", "dea D IY1 IY1 EY1", "swat S W AA1 T",
    "nasa N AE1 S AH0", "asap EY1 EH1 S EY1 P IY1", "vip V IY1 AY1 P IY1", "ceo S IY1 IY1 OW1",
    "atm EY1 T IY1 EH1 M", "usa Y UW1 EH1 S EY1", "id AY1 D IY1", "dui D IY1 Y UW1 AY1", "apb EY1 P IY1 B IY1",
    "lol EH1 L OW1 EH1 L", "omg OW1 EH1 M JH IY1",
    "bowl B OW1 L", "canoe K AH0 N UW1", "shoe SH UW1", "shoes SH UW1 Z", "toe T OW1",
};

static const char* const kLetterNames[26] = {
    "EY1", "B IY1", "S IY1", "D IY1", "IY1", "EH1 F", "JH IY1", "EY1 CH", "AY1", "JH EY1", "K EY1", "EH1 L",
    "EH1 M", "EH1 N", "OW1", "P IY1", "K Y UW1", "AA1 R", "EH1 S", "T IY1", "Y UW1", "V IY1",
    "D AH1 B AH0 L Y UW0", "EH1 K S", "W AY1", "Z IY1",
};

struct DictMap {
    std::unordered_map<std::string, const char*> map;
};

static DictMap buildDict() {
    DictMap d;
    d.map.reserve(ARRAY_COUNT(kDictEntries) * 2);
    for (size_t i = 0; i < ARRAY_COUNT(kDictEntries); i++) {
        const char* e = kDictEntries[i];
        const char* sp = strchr(e, ' ');
        if (!sp) continue;
        std::string w(e, (size_t)(sp - e));
        if (d.map.find(w) == d.map.end()) d.map.emplace(w, sp + 1);  // first entry wins
    }
    return d;
}

static const DictMap& dict() {
    static const DictMap d = buildDict();  // thread-safe one-time init, read-only afterwards
    return d;
}

const char* dictLookup(const std::string& w) {
    const DictMap& d = dict();
    auto it = d.map.find(w);
    return it == d.map.end() ? nullptr : it->second;
}

bool isFunctionWord(const std::string& w) {
    const char* p = dictLookup(w);
    return p && p[0] == '~';
}

void spellWord(const std::string& word, Pron& out) {
    int start = (int)out.size();
    for (char c : word) {
        if (c >= 'a' && c <= 'z') parsePhonemes(kLetterNames[c - 'a'], out);
        else if (c >= 'A' && c <= 'Z') parsePhonemes(kLetterNames[c - 'A'], out);
    }
    // Only the last letter keeps primary stress; earlier ones get secondary (natural acronym prosody).
    int lastV = -1;
    for (int i = start; i < (int)out.size(); i++)
        if (isVowel(out[i].ph) && out[i].stress == 1) lastV = i;
    for (int i = start; i < lastV; i++)
        if (isVowel(out[i].ph) && out[i].stress == 1) out[i].stress = 2;
}

}  // namespace detail
}  // namespace Speech
